export const schoolInfo = {
  name: "Jizzax shahridagi 1-sonli ixtisoslashtirilgan maktab-internati",
  shortName: "1-IMI Jizzax",
  founded: 2022,
  address: "Jizzax shahri, A. Temur ko'chasi, 12-uy",
  phone: "+998 (72) 226-45-67",
  phone2: "+998 (72) 226-45-68",
  email: "info@jizzax1-maktab.uz",
  mapUrl: "https://www.google.com/maps/search/?api=1&query=Jizzax+shahar+1+ixtisoslashtirilgan+maktab",
  mapEmbed: "https://www.google.com/maps?q=Jizzakh%20Uzbekistan&output=embed",
  social: {
    telegram: "https://t.me/jizzax1_maktab",
    youtube: "https://youtube.com/@jizzax1maktab",
    instagram: "https://instagram.com/jizzax1_maktab",
    facebook: "https://facebook.com/jizzax1maktab",
  },
};

export const stats = [
  { label: "O'quvchilar", value: 450, suffix: "+" },
  { label: "O'qituvchilar", value: 48, suffix: "" },
  { label: "Chuqurlashtirilgan fanlar", value: 5, suffix: "" },
  { label: "Yutuqlar (2024)", value: 23, suffix: "" },
  { label: "Birinchi bitiruvchilar", value: 120, suffix: "+" },
  { label: "Oliy o'quv muassasalariga kirish", value: 94, suffix: "%" },
];

export const historyTimeline = [
  {
    year: "2022",
    title: "Maktab tashkil etilishi",
    description:
      "Jizzax shahrida iqtidorli o'quvchilar uchun 1-sonli ixtisoslashtirilgan maktab-internati tashkil etildi. Zamonaviy kampus, laboratoriyalar va sport zali bilan 450 nafar o'quvchiga mo'ljallangan holda faoliyat boshladi.",
  },
  {
    year: "2022",
    title: "Chuqurlashtirilgan dastur va innovatsiya markazi",
    description:
      "Matematika, fizika va informatika bo'yicha chuqurlashtirilgan o'quv dasturlari joriy etildi. Bir vaqtning o'zida STEM innovatsiya markazi ochildi — robototexnika, sun'iy intellekt va 3D modellashtirish to'garaklari tashkil etildi.",
  },
  {
    year: "2023",
    title: "Xalqaro hamkorlik",
    description:
      "Turkiya va Qozog'istondagi nufuzli maktablar bilan almashinuv dasturi boshlandi. Cambridge English sertifikatlash markazi ochildi. Birinchi o'quvchilar respublika olimpiadalarida g'olib bo'ldi.",
  },
  {
    year: "2024",
    title: "Prezident Devoni",
    description:
      "O'quvchilar o'zini-o'zi boshqarish tizimi sifatida 6 ta vazirlikdan iborat Prezident Devoni tashkil etildi. O'quvchilarning tashabbuskorlik va yetakchilik mahorati rivojlantirildi.",
  },
  {
    year: "2025",
    title: "Raqamli maktab",
    description:
      "To'liq raqamli maktab portaliga o'tish amalga oshirildi. Video darslar arxivi, onlayn GPA reytingi va ota-onalar kuzatuvi tizimi ishga tushdi. Birinchi bitiruvchilar oliy o'quv muassasalariga muvaffaqiyatli kirdi.",
  },
];

export const goals = [
  {
    icon: "Target",
    title: "Akademik mukammallik",
    description:
      "O'quvchilarni chuqur bilim, tanqidiy fikrlash va ijodiy yondashuv bilan qurollantirish. Har bir o'quvchining salohiyatini to'liq ochish.",
  },
  {
    icon: "Lightbulb",
    title: "Innovatsion tafakkur",
    description:
      "STEM, robototexnika va yangi texnologiyalar orqali o'quvchilarni kelajak kasblariga tayyorlash. Tadqiqot va loyiha asosida o'qitish.",
  },
  {
    icon: "Heart",
    title: "Vatanga muhabbat",
    description:
      "Milliy g'urur, fuqarolik mas'uliyati va jamiyat oldidagi burchini chuqur his qiladigan, harakatchan yoshlarni tarbiyalash.",
  },
  {
    icon: "Users",
    title: "Yetakchilik mahorati",
    description:
      "Prezident Devoni orqali o'quvchilarning yetakchilik, jamoa boshqaruvi va qaror qabul qilish ko'nikmalarini rivojlantirish.",
  },
];

export interface Teacher {
  id: string;
  name: string;
  role: string;
  bio: string;
  image: string;
  reception?: string;
  phone?: string;
  subject?: string;
  classes?: string;
  experience?: string;
  category?: string;
}

export const administration: Teacher[] = [
  {
    id: "admin-1",
    name: "Suyarova Sanobar Zarfullayevna",
    role: "Maktab direktori",
    bio: "Maktab rahbari. Taʼlim tizimida boshqaruv va pedagogik tajribaga ega.",
    image: "/images/dr.jpg",
    reception: "Har kuni 10:00 — 14:00",
    phone: "+998 90 229 14 30",
  },
  {
    id: "admin-2",
    name: "Bobobekova Shoira Ibodullayevna",
    role: "O'quv ishlari bo'yicha direktor o'rinbosari",
    bio: "O'quv jarayonini muvofiqlashtirish va ta'lim sifatini oshirish bo'yicha mas'ul rahbar.",
    image: "/images/shoira.jpg",
    reception: "Har kuni 11:00 — 15:00",
    phone: "+998 95 970 98 09",
  },
  {
    id: "admin-3",
    name: "Turabov Farrux Abdusalomovich",
    role: "Ma'naviy-ma'rifiy ishlar bo'yicha direktor o'rinbosari",
    bio: "Yoshlarni tarbiyalash, ma'naviy-ma'rifiy tadbirlarni tashkil etish bo'yicha mas'ul rahbar.",
    image: "/images/farrux.jpg",
    reception: "Har kuni 12:00 — 16:00",
    phone: "+998 90 538 39 25",
  },
  {
    id: "admin-4",
    name: "Berdibekova Jamila Asatullayevna",
    role: "Maktab maslahatchisi",
    bio: "O'quvchilar va jamoa o'rtasida ijtimoiy-psixologik muhitni qo'llab-quvvatlovchi maslahatchi.",
    image: "/images/jamila.jpg",
    reception: "Har kuni 10:30 — 15:30",
    phone: "+998 91 569 08 12",
  },
  {
    id: "admin-5",
    name: "Eshonqulova Xulkar Abduvahobovna",
    role: "Maktab psixologi",
    bio: "Taʼlim tizimida o‘smirlar psixologiyasi va o‘quvchilar bilan ishlash bo‘yicha katta tajribaga ega mutaxassis.",
    image: "/images/default.jpg",
    reception: "Har kuni 09:00 — 13:00",
    phone: "+998 91 555 01 23",
  },
  {
    id: "admin-6",
    name: "Pardayeva Gulshan O'ktamovna",
    role: "Maktab kadrlar bo‘yicha menejeri",
    bio: "Maʼmuriy boshqaruv va kadrlar hisobi tizimida katta tajribaga ega mutaxassis.",
    image: "/images/default.jpg",
    reception: "Har kuni 09:00 — 17:00",
    phone: "+998 93 333 44 55",
  },
  {
    id: "admin-7",
    name: "Tursumatova Zamira Xasantayevna",
    role: "Maktab bosh hisobchisi",
    bio: "Moliya va buxgalteriya sohasida tajribaga ega bosh hisobchi.",
    image: "/images/default.jpg",
    reception: "Dushanba - Juma 09:00 — 16:00",
    phone: "+998 90 111 22 33",
  },
  {
    id: "admin-8",
    name: "Xushbaqov Sherzod Qahorovich",
    role: "Xo'jalik ishlari bo'yicha direktor o'rinbosari",
    bio: "Xo'jalik va ta'minot ishlarini muvofiqlashtiruvchi mas'ul rahbar.",
    image: "/images/default.jpg",
    reception: "Har kuni 08:00 — 17:00",
    phone: "+998 99 777 88 99",
  },
];

export const teachers: Teacher[] = [
  {
    id: "t-1",
    name: "Abdullayeva Nigora Askarovna",
    role: "Ona tili va adabiyot fani o'qituvchisi",
    bio: "Taʼlim sohasida 30 yildan ortiq tajribaga ega pedagog.",
    image: "/images/default.jpg",
    subject: "Ona tili va adabiyot",
    classes: "5-A, 7-B, 9-A",
    experience: "30 yil",
    category: "Oliy toifa",
  },
  {
    id: "t-2",
    name: "Abdurasulova Munira Husan qizi",
    role: "Ingliz tili fani o'qituvchisi",
    bio: "Ingliz tili fani o‘qituvchisi.",
    image: "/images/default.jpg",
    subject: "Ingliz tili",
    classes: "6-B, 8-A, 10-V",
    experience: "8 yil",
    category: "Birinchi toifa",
  },
  {
    id: "t-3",
    name: "Adashboyev Jaloliddin Nabi o‘g‘li",
    role: "Informatika fani o‘qituvchisi",
    bio: "Kompyuter grafikasi va informatika yo'nalishida dars beradi.",
    image: "/images/default.jpg",
    subject: "Informatika",
    classes: "7-A, 9-B, 11-A",
    experience: "6 yil",
    category: "Mutaxassis",
  },
  {
    id: "t-4",
    name: "Aralova Gulchexra Kuchkarovna",
    role: "Rus tili fani o‘qituvchisi",
    bio: "35 yildan ortiq tajribaga ega pedagog.",
    image: "/images/default.jpg",
    subject: "Rus tili",
    classes: "5-V, 8-B, 10-A",
    experience: "35 yil",
    category: "Oliy toifa",
  },
  {
    id: "t-5",
    name: "Asrayev Saidazim Ulug‘bek o‘g‘li",
    role: "Matematika fani o‘qituvchisi",
    bio: "Matematika fanidan chuqurlashtirilgan darslar o'tadi.",
    image: "/images/default.jpg",
    subject: "Matematika",
    classes: "6-A, 9-A, 11-B",
    experience: "7 yil",
    category: "Birinchi toifa",
  },
  {
    id: "t-6",
    name: "Ashurova Feruza Oltiboyevna",
    role: "Ingliz tili fani o‘qituvchisi",
    bio: "25 yildan ortiq tajribaga ega pedagog.",
    image: "/images/default.jpg",
    subject: "Ingliz tili",
    classes: "7-B, 8-V, 10-B",
    experience: "25 yil",
    category: "Oliy toifa",
  },
  {
    id: "t-7",
    name: "Bobojanova Dilafruz Murodovna",
    role: "Ona tili va adabiyot fani o‘qituvchisi",
    bio: "20 yildan ortiq tajribaga ega pedagog.",
    image: "/images/default.jpg",
    subject: "Ona tili va adabiyot",
    classes: "5-A, 6-V, 9-V",
    experience: "20 yil",
    category: "Oliy toifa",
  },
  {
    id: "t-8",
    name: "Yodgorov Erkin Yodgor o‘g‘li",
    role: "Fizika fani o‘qituvchisi",
    bio: "Fizika fanidan tajribali o'qituvchi.",
    image: "/images/default.jpg",
    subject: "Fizika",
    classes: "8-A, 10-A, 11-A",
    experience: "12 yil",
    category: "Birinchi toifa",
  },
  {
    id: "t-9",
    name: "Kamolova Madina O‘tkir qizi",
    role: "O‘qituvchi",
    bio: "O‘zMU magistratura bitiruvchisi.",
    image: "/images/default.jpg",
    subject: "Matematika",
    classes: "5-B, 7-A, 9-B",
    experience: "4 yil",
    category: "Mutaxassis",
  },
  {
    id: "t-10",
    name: "Kochurova Anastasiya Alekseyevna",
    role: "Ingliz tili fani o‘qituvchisi",
    bio: "'Xalq ta’limi a’lochisi' ko‘krak nishoni sohibasi.",
    image: "/images/default.jpg",
    subject: "Ingliz tili",
    classes: "6-A, 9-A, 11-V",
    experience: "18 yil",
    category: "Oliy toifa",
  },
  {
    id: "t-11",
    name: "Maqsudova Madinaxon Qayumxonovna",
    role: "Matematika fani o‘qituvchisi",
    bio: "Namangan davlat universiteti bitiruvchisi.",
    image: "/images/default.jpg",
    subject: "Matematika",
    classes: "5-A, 8-B, 10-V",
    experience: "9 yil",
    category: "Birinchi toifa",
  },
  {
    id: "t-12",
    name: "Mamatqulov Shuxrat Rasulberdiyevich",
    role: "Tarix fani o‘qituvchisi",
    bio: "Tarix fanidan dars beradi.",
    image: "/images/default.jpg",
    subject: "Tarix",
    classes: "7-V, 9-V, 11-B",
    experience: "14 yil",
    category: "Birinchi toifa",
  },
  {
    id: "t-13",
    name: "Mamasharipova Xurshida Tugalovna",
    role: "Biologiya fani o‘qituvchisi",
    bio: "20 yillik tajribaga ega pedagog.",
    image: "/images/default.jpg",
    subject: "Biologiya",
    classes: "8-A, 10-B, 11-A",
    experience: "20 yil",
    category: "Oliy toifa",
  },
  {
    id: "t-14",
    name: "Mansurov Zafar Yupusjanovich",
    role: "Tarbiya fani o‘qituvchisi",
    bio: "Tarbiya va huquq fani o‘qituvchisi.",
    image: "/images/default.jpg",
    subject: "Tarbiya",
    classes: "5-V, 6-B, 8-V",
    experience: "11 yil",
    category: "Birinchi toifa",
  },
  {
    id: "t-15",
    name: "Aliyev Murod G‘ani o‘g‘li",
    role: "Biologiya fani o‘qituvchisi",
    bio: "Biologiya fanidan dars beradi.",
    image: "/images/default.jpg",
    subject: "Biologiya",
    classes: "7-A, 9-A, 10-A",
    experience: "5 yil",
    category: "Ikkinchi toifa",
  },
  {
    id: "t-16",
    name: "Jumayev Bobomurod Nishanovich",
    role: "Matematika fani o‘qituvchisi",
    bio: "Matematika fanidan tajribali ustoz.",
    image: "/images/default.jpg",
    subject: "Matematika",
    classes: "6-A, 8-B, 11-V",
    experience: "16 yil",
    category: "Oliy toifa",
  },
  {
    id: "t-17",
    name: "Qo‘nishev Azamat Ravshan o‘g‘li",
    role: "Matematika fani o‘qituvchisi",
    bio: "Matematika fani o'qituvchisi.",
    image: "/images/default.jpg",
    subject: "Matematika",
    classes: "5-B, 7-B, 10-B",
    experience: "6 yil",
    category: "Mutaxassis",
  },
  {
    id: "t-18",
    name: "Majidova Gulshoda Sharafiddinovna",
    role: "Biologiya fani o‘qituvchisi",
    bio: "Biologiya fanidan magistr o'qituvchi.",
    image: "/images/default.jpg",
    subject: "Biologiya",
    classes: "8-A, 9-V, 11-A",
    experience: "9 yil",
    category: "Birinchi toifa",
  },
  {
    id: "t-19",
    name: "Murtazina Diana Raxibovna",
    role: "Ingliz tili fani o‘qituvchisi",
    bio: "Ingliz tili o'qituvchisi.",
    image: "/images/default.jpg",
    subject: "Ingliz tili",
    classes: "5-A, 6-B, 7-A",
    experience: "7 yil",
    category: "Ikkinchi toifa",
  },
  {
    id: "t-20",
    name: "Nazirov Javoxirbek Shodiyor o‘g‘li",
    role: "Matematika fani o‘qituvchisi",
    bio: "Matematika fani o'qituvchisi.",
    image: "/images/default.jpg",
    subject: "Matematika",
    classes: "8-B, 9-A, 10-V",
    experience: "5 yil",
    category: "Mutaxassis",
  },
  {
    id: "t-21",
    name: "Sadikov Nasim Xusanboyevich",
    role: "Ingliz tili fani o‘qituvchisi",
    bio: "O‘zDJTU magistri, ingliz tili o'qituvchisi.",
    image: "/images/default.jpg",
    subject: "Ingliz tili",
    classes: "9-B, 10-A, 11-B",
    experience: "10 yil",
    category: "Birinchi toifa",
  },
  {
    id: "t-22",
    name: "Umarova Dilafruz Umurzoqovna",
    role: "Kimyo fani o‘qituvchisi",
    bio: "Kimyo fani o'qituvchisi.",
    image: "/images/default.jpg",
    subject: "Kimyo",
    classes: "8-A, 9-V, 11-A",
    experience: "13 yil",
    category: "Birinchi toifa",
  },
  {
    id: "t-23",
    name: "Xo‘shbaqov Ulug‘bek Abdumajid o‘g‘li",
    role: "Axborot texnologiyalari va matematika fani o‘qituvchisi",
    bio: "TATU bitiruvchisi, IT va matematika o'qituvchisi.",
    image: "/images/default.jpg",
    subject: "Informatika va matematika",
    classes: "7-B, 10-B, 11-V",
    experience: "8 yil",
    category: "Birinchi toifa",
  },
  {
    id: "t-24",
    name: "Ochilova Shahlo Nosirovna",
    role: "Rus tili va adabiyoti fani o‘qituvchisi",
    bio: "Rus tili va adabiyoti fani o'qituvchisi.",
    image: "/images/default.jpg",
    subject: "Rus tili va adabiyoti",
    classes: "5-V, 6-A, 8-B",
    experience: "15 yil",
    category: "Oliy toifa",
  },
  {
    id: "t-25",
    name: "Rustamov Akbarjon Muhammadiyevich",
    role: "Jismoniy tarbiya fani o‘qituvchisi",
    bio: "Jismoniy tarbiya o'qituvchisi.",
    image: "/images/default.jpg",
    subject: "Jismoniy tarbiya",
    classes: "5-A, 7-A, 9-A",
    experience: "12 yil",
    category: "Birinchi toifa",
  },
  {
    id: "t-26",
    name: "Suvonqulov Dilshod Maxmud o‘g‘li",
    role: "Informatika fani o‘qituvchisi",
    bio: "Informatika fani o'qituvchisi.",
    image: "/images/default.jpg",
    subject: "Informatika",
    classes: "8-A, 10-A, 11-B",
    experience: "6 yil",
    category: "Mutaxassis",
  },
  {
    id: "t-27",
    name: "Tashnazarova Shahnoza Bahodir qizi",
    role: "Tasviriy san’at va chizmachilik fani o‘qituvchisi",
    bio: "Tasviriy san'at va chizmachilik o'qituvchisi.",
    image: "/images/default.jpg",
    subject: "Tasviriy san'at va chizmachilik",
    classes: "5-B, 6-B, 7-V",
    experience: "5 yil",
    category: "Ikkinchi toifa",
  },
  {
    id: "t-28",
    name: "Turdiyeva Nargiza Mansurovna",
    role: "Rus tili va adabiyoti fani o‘qituvchisi",
    bio: "Rus tili va adabiyoti o'qituvchisi.",
    image: "/images/default.jpg",
    subject: "Rus tili va adabiyoti",
    classes: "7-A, 9-B, 10-V",
    experience: "14 yil",
    category: "Birinchi toifa",
  },
  {
    id: "t-29",
    name: "Tyan Elena Yevgenyevna",
    role: "Ingliz tili fani o‘qituvchisi",
    bio: "Ingliz tili o'qituvchisi.",
    image: "/images/default.jpg",
    subject: "Ingliz tili",
    classes: "5-A, 8-V, 11-A",
    experience: "17 yil",
    category: "Oliy toifa",
  },
  {
    id: "t-30",
    name: "Usmanov Navruz Asanboy o‘g‘li",
    role: "Tarix fani o‘qituvchisi",
    bio: "Tarix fani o'qituvchisi.",
    image: "/images/default.jpg",
    subject: "Tarix",
    classes: "6-A, 8-A, 10-B",
    experience: "7 yil",
    category: "Ikkinchi toifa",
  },
  {
    id: "t-31",
    name: "Xolboyev Humoyun Baxtiyor o‘g‘li",
    role: "Matematika fani o‘qituvchisi",
    bio: "Matematika fani o'qituvchisi.",
    image: "/images/default.jpg",
    subject: "Matematika",
    classes: "7-B, 9-A, 11-V",
    experience: "6 yil",
    category: "Mutaxassis",
  },
  {
    id: "t-32",
    name: "Xursanov Bobur Rahmatullayevich",
    role: "Fizika va astronomiya fani o‘qituvchisi",
    bio: "Fizika va astronomiya o'qituvchisi.",
    image: "/images/default.jpg",
    subject: "Fizika va astronomiya",
    classes: "8-B, 10-A, 11-B",
    experience: "11 yil",
    category: "Birinchi toifa",
  },
  {
    id: "t-33",
    name: "Saidova Gulnoza Toshpo'latovna",
    role: "Fizika fani o‘qituvchisi",
    bio: "Fizika fanidan chuqurlashtirilgan darslar o'tadi.",
    image: "/images/default.jpg",
    subject: "Fizika",
    classes: "7-A, 9-V, 11-A",
    experience: "15 yil",
    category: "Oliy toifa",
  },
  {
    id: "t-34",
    name: "Ergashev Jamshid Po'latovich",
    role: "Informatika fani o‘qituvchisi",
    bio: "Informatika va dasturlash yo'nalishi o'qituvchisi.",
    image: "/images/default.jpg",
    subject: "Informatika",
    classes: "8-A, 10-V, 11-B",
    experience: "9 yil",
    category: "Birinchi toifa",
  },
];

export const subjects = [
  { 
    name: "Matematika", 
    icon: "Calculator", 
    color: "blue", 
    desc: "Chuqurlashtirilgan matematika dasturi — algebra, geometriya va matematik analiz asoslari." 
  },
  { 
    name: "Ingliz tili", 
    icon: "Languages", 
    color: "blue", 
    desc: "Cambridge English standartlari asosida IELTS va CEFR darajalariga tayyorgarlik." 
  },
  { 
    name: "Fizika", 
    icon: "Atom", 
    color: "green", 
    desc: "Mexanika, elektr va optika bo'yicha laboratoriya tajribalari bilan chuqurlashtirilgan kurs." 
  },
  { 
    name: "Biologiya", 
    icon: "Dna", 
    color: "green", 
    desc: "Genetika, mikrobiologiya va ekologiya bo'yicha zamonaviy tadqiqot usullari." 
  },
  { 
    name: "Kimyo", 
    icon: "FlaskConical", 
    color: "red", 
    desc: "Organik va noorganik kimyo, laboratoriya amaliyotlari va ilmiy loyihalar." 
  },
];

export const gpaRankings = [
  { rank: 1, name: "Abdullayev Sardor", class: "11-A", gpa: 4.97, achievements: 8 },
  { rank: 2, name: "Xolmatova Aziza", class: "11-A", gpa: 4.95, achievements: 7 },
  { rank: 3, name: "Saidov Jahongir", class: "11-B", gpa: 4.93, achievements: 6 },
  { rank: 4, name: "Ergasheva Nilufar", class: "10-A", gpa: 4.91, achievements: 5 },
  { rank: 5, name: "Tursunov Bekzod", class: "11-A", gpa: 4.89, achievements: 6 },
  { rank: 6, name: "Karimova Shahnoza", class: "10-B", gpa: 4.87, achievements: 4 },
  { rank: 7, name: "Rahimov Jasur", class: "11-B", gpa: 4.85, achievements: 5 },
  { rank: 8, name: "Yusupova Madina", class: "10-A", gpa: 4.83, achievements: 3 },
  { rank: 9, name: "Toshmatov Dilmurod", class: "11-A", gpa: 4.81, achievements: 4 },
  { rank: 10, name: "Hakimova Barno", class: "10-B", gpa: 4.79, achievements: 3 },
];

export const videoLessons = [
  { title: "Matematik analiz: Cheklovlar va hosilalar", teacher: "Azizov Shuhrat E.", subject: "Matematika", duration: "32:15", youtubeId: "dQw4w9WgXcQ", thumbnail: "https://images.pexels.com/photos/2566581/pexels-photo-2566581.jpeg?auto=compress&cs=tinysrgb&w=600" },
  { title: "Mexanika: Nyuton qonunlari va ularning qo'llanishi", teacher: "Saidova Gulnoza T.", subject: "Fizika", duration: "28:40", youtubeId: "kKKMjpY7O9A", thumbnail: "https://images.pexels.com/photos/256541/pexels-photo-256541.jpeg?auto=compress&cs=tinysrgb&w=600" },
  { title: "Python dasturlash: Funksiyalar va ro'yxatlar", teacher: "Ergashev Jamshid P.", subject: "Informatika", duration: "45:20", youtubeId: "k3V0z5U2z3k", thumbnail: "https://images.pexels.com/photos/270404/pexels-photo-270404.jpeg?auto=compress&cs=tinysrgb&w=600" },
  { title: "Organik kimyo: Uglevodorodlar va izomeriya", teacher: "Hakimov Otabek N.", subject: "Kimyo", duration: "36:55", youtubeId: "bORHxJ2_zDs", thumbnail: "https://images.pexels.com/photos/256381/pexels-photo-256381.jpeg?auto=compress&cs=tinysrgb&w=600" },
  { title: "Genetika: Mendel qonunlari va DNK tuzilishi", teacher: "Yuldasheva Barno Q.", subject: "Biologiya", duration: "31:10", youtubeId: "Meh5b9q0rHk", thumbnail: "https://images.pexels.com/photos/256298/pexels-photo-256298.jpeg?auto=compress&cs=tinysrgb&w=600" },
  { title: "IELTS Writing Task 2: Essay tuzilishi", teacher: "Toshmatova Dilfuza R.", subject: "Ingliz tili", duration: "40:05", youtubeId: "WUiv2cU9sJQ", thumbnail: "https://images.pexels.com/photos/256541/pexels-photo-256541.jpeg?auto=compress&cs=tinysrgb&w=600" },
];

export const videos = videoLessons;

export const projects = [
  {
    title: "Kinetik velosiped generatori",
    category: "Energetika",
    year: 2024,
    description: "O'quvchilar tomonidan ishlab chiqilgan kinetik velosiped generatori — velosiped pedallari aylanganda elektr energiyasi hosil qilib, uni akkumulyatorda to'playdigan va LED yoritish tizimini ta'minlaydigan innovatsion loyiha.",
    impact: "Kuniga 200 Vt-soat energiya tejash",
    image: "https://images.pexels.com/photos/1000653/pexels-photo-1000653.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    title: "Aqlli sug'orish tizimi",
    category: "Ekologiya",
    year: 2023,
    description: "Mikrokontroller asosida ishlovchi avtomatik sug'orish tizimi — tuproq namligini o'lchab, o'simliklarga kerakli miqdorda suv beradi. Maktab oshxonasidagi o'tkinchi bog'da muvaffaqiyatli qo'llanilmoqda.",
    impact: "Suv sarfini 40% kamaytirish",
    image: "https://images.pexels.com/photos/1072824/pexels-photo-1072824.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    title: "Sun'iy intellekt chat-bot",
    category: "IT",
    year: 2024,
    description: "O'quvchilar uchun o'qish jarayonini qo'llab-quvvatlovchi AI chat-bot — fan bo'yicha savollarga javob beradi, qo'shimcha materiallar tavsiya qiladi va o'qish jadvalini eslatadi.",
    impact: "500+ faol foydalanuvchi",
    image: "https://images.pexels.com/photos/8386440/pexels-photo-8386440.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
  {
    title: "Ekologik tozalash aksiyasi",
    category: "Ijtimoiy",
    year: 2024,
    description: "Maktab o'quvchilari tashabbusi bilan tashkil etilgan shahar miqyosidagi ekologik tozalash aksiyasi. 200+ o'quvchi va 50+ ko'ngilli ishtirok etib, 5 tonna chiqindini to'pladi va saraladi.",
    impact: "5 tonna chiqindi qayta ishlandi",
    image: "https://images.pexels.com/photos/296301/pexels-photo-296301.jpeg?auto=compress&cs=tinysrgb&w=600",
  },
];

export const socialActions = [
  { label: "Daraxt ekkan o'quvchilar", value: 1200, suffix: "+" },
  { label: "Tozalash aksiyalari", value: 18, suffix: "" },
  { label: "Xayriya yig'ilgan (mln so'm)", value: 15, suffix: "" },
  { label: "Ijtimoiy loyihalar", value: 24, suffix: "" },
];

export const schoolPresident = {
  name: "Shamsiddinov Shohruz",
  telegram: "shamsiddinovshohruz",
  role: "Maktab Prezidenti",
  description: "O'zini-o'zi boshqarish tizimining rahbari — barcha vazirliklar faoliyatini muvofiqlashtirish, maktab jamoasi manfaatlarini himoya qilish va strategik qarorlar qabul qilish.",
};

export const ministries = [
  {
    name: "Ta'lim Vazirligi",
    icon: "GraduationCap",
    color: "blue",
    minister: "Xusanov Samariddin",
    telegram: "gottalove_SAM",
    description: "Bilim sifatini oshirish va o'quv faoliyatini nazorat qilish. Olimpiada va tanlovlarga tayyorgarlik, o'qituvchilar bilan hamkorlik.",
    initiatives: ["Matematika olimpiadasi", "Kitobxonlik klubi", "O'qituvchilar bahori"],
  },
  {
    name: "Innovatsiya Vazirligi",
    icon: "Rocket",
    color: "blue",
    minister: "Axmadjonov Bexruz",
    telegram: "ANEERUTTY",
    description: "Zamonaviy texnologiyalar, startaplar va yangi g'oyalarni joriy etish. STEM loyihalarini boshqarish, texnologik tanlovlar o'tkazish.",
    initiatives: ["Robototexnika klubi", "Startap haftaligi", "AI tanlovi"],
  },
  {
    name: "Sport Vazirligi",
    icon: "Trophy",
    color: "orange",
    minister: "Javlon Orifjonov",
    telegram: "javlonorifjonov",
    description: "Sog'lom turmush tarzi va musobaqalarni tashkil etish. Maktab terma jamoalarini boshqarish va sport tadbirlarini o'tkazish.",
    initiatives: ["Futbol ligasi", "Shaxmat turniri", "Sport kunlari"],
  },
  {
    name: "Moliya Vazirligi",
    icon: "Wallet",
    color: "green",
    minister: "Jasurbek Xoltemirov",
    telegram: "kh0ltem1r0v",
    description: "Loyihalarni iqtisodiy asoslash va resurslar hisobi. Maktab byudjetini rejalashtirish, xarajatlarni nazorat qilish va moliyaviy hisobotlar.",
    initiatives: ["Loyiha byudjetlari", "Moliyaviy hisobot", "Resurslar taqsimoti"],
  },
  {
    name: "Madaniyat Vazirligi",
    icon: "Palette",
    color: "red",
    minister: "Asatullayev Jamshid",
    telegram: "jamshid_ool",
    description: "Ma'naviy-ma'rifiy tadbirlar va ijodiy loyihalar. Teatr to'garaklari, musiqa kechalari va milliy urf-odatlarni saqlash.",
    initiatives: ["Teatr studiyasi", "Navro'z bayrami", "She'riyat oqshomi"],
  },
  {
    name: "Ekologiya Vazirligi",
    icon: "Leaf",
    color: "green",
    minister: "Izzatbek Soatov",
    telegram: "LucidDrifter",
    description: "Atrof-muhit muhofazasi va tozalikni saqlash. Daraxt ekish aksiyalari, chiqindini saralash va ekologik ta'lim.",
    initiatives: ["Daraxt ekish aksi", "Chiqindi saralash", "Ekologik olimpiada"],
  },
  {
    name: "Kommunikatsiya Vazirligi",
    icon: "MessageCircle",
    color: "orange",
    minister: "Anvar Sayfidinov",
    telegram: "sayfidinov_009",
    description: "SMM boshqaruv, rasmiy kanallar, dizayn va jamoaaro aloqalar. Maktab ijtimoiy tarmoqlarini boshqarish va yangiliklar chiqarish.",
    initiatives: ["Maktab gazetasi", "Telegram kanal", "Media studiya"],
  },
];

export const galleryItems = [
  { type: "photo", url: "https://images.pexels.com/photos/8617715/pexels-photo-8617715.jpeg?auto=compress&cs=tinysrgb&w=600", title: "Bitiruvchilar kuni 2024" },
  { type: "photo", url: "https://images.pexels.com/photos/8617872/pexels-photo-8617872.jpeg?auto=compress&cs=tinysrgb&w=600", title: "Olimpiada g'oliblari" },
  { type: "photo", url: "https://images.pexels.com/photos/5212345/pexels-photo-5212345.jpeg?auto=compress&cs=tinysrgb&w=600", title: "O'qituvchilar jamoasi" },
  { type: "photo", url: "https://images.pexels.com/photos/2566581/pexels-photo-2566581.jpeg?auto=compress&cs=tinysrgb&w=600", title: "Matematika darsi" },
  { type: "photo", url: "https://images.pexels.com/photos/8386440/pexels-photo-8386440.jpeg?auto=compress&cs=tinysrgb&w=600", title: "Robototexnika to'garagi" },
  { type: "photo", url: "https://images.pexels.com/photos/296301/pexels-photo-296301.jpeg?auto=compress&cs=tinysrgb&w=600", title: "Ekologik aksiya" },
  { type: "photo", url: "https://images.pexels.com/photos/1000653/pexels-photo-1000653.jpeg?auto=compress&cs=tinysrgb&w=600", title: "Kinetik velosiped loyihasi" },
  { type: "photo", url: "https://images.pexels.com/photos/1072824/pexels-photo-1072824.jpeg?auto=compress&cs=tinysrgb&w=600", title: "Aqlli sug'orish tizimi" },
  { type: "photo", url: "https://images.pexels.com/photos/256381/pexels-photo-256381.jpeg?auto=compress&cs=tinysrgb&w=600", title: "Kimyo laboratoriyasi" },
  { type: "photo", url: "https://images.pexels.com/photos/256298/pexels-photo-256298.jpeg?auto=compress&cs=tinysrgb&w=600", title: "Biologiya tajribasi" },
  { type: "photo", url: "https://images.pexels.com/photos/256541/pexels-photo-256541.jpeg?auto=compress&cs=tinysrgb&w=600", title: "Fizika laboratoriyasi" },
  { type: "photo", url: "https://images.pexels.com/photos/270404/pexels-photo-270404.jpeg?auto=compress&cs=tinysrgb&w=600", title: "Informatika xonasi" },
];

export const navLinks = [
  { label: "Bosh sahifa", href: "#hero" },
  { label: "Maktab haqida", href: "#about" },
  { label: "Akademik", href: "#academic" },
  { label: "Ma'muriyat", href: "#administration" },
  { label: "Video darsliklar", href: "#videolessons" },
  { label: "Prezident Devoni", href: "#president" },
  { label: "Innovatsiya", href: "#innovation" },
  { label: "Galereya", href: "#gallery" },
  { label: "Aloqa", href: "#contact" },
];