import { FormEvent, useEffect, useState } from 'react';
import { AlertTriangle, BedDouble, ChevronDown, ChevronUp, Coins, LogIn, LogOut, Pencil, Plus, RefreshCw, Save, ShieldCheck, Trash2, Upload, X } from 'lucide-react';
import SchoolCoinSecure from './SchoolCoinSecure';
import { getSiteData, saveSiteData, signInAdmin, signOutAdmin, supabase } from '../lib/supabase';

interface Props { onClose: () => void; }
type Primitive = string | number | boolean | null | undefined;
type Key = 'teachers' | 'projects' | 'galleryList' | 'videoLessons' | 'announcements' | 'birthdays' | 'gpaList';
type Item = Record<string, Primitive> & { id?: string | number };
type Meal = { id?: string; name: string; time: string; description?: string };
type Routine = { id?: string; time: string; activity: string; description?: string };
type SchoolLifeData = { dormitory: { title: string; description: string; image: string; features: string[] }; meals: { title: string; description: string; menu: Meal[] }; routine: { title: string; description: string; items: Routine[] } };

const sections: Array<{ key: Key; label: string }> = [
  { key: 'teachers', label: "O'qituvchilar" }, { key: 'projects', label: 'Loyihalar' }, { key: 'galleryList', label: 'Galereya' },
  { key: 'videoLessons', label: 'Video darslar' }, { key: 'announcements', label: "E'lonlar" }, { key: 'birthdays', label: "Tug'ilgan kunlar" }, { key: 'gpaList', label: 'GPA' },
];
const fields: Record<Key, Array<{ key: string; label: string; type?: string; required?: boolean }>> = {
  teachers: [{ key: 'name', label: 'Ism-familiya', required: true }, { key: 'subject', label: 'Fan', required: true }, { key: 'role', label: 'Lavozim' }, { key: 'experience', label: 'Tajriba' }, { key: 'classes', label: 'Sinflar' }, { key: 'category', label: 'Toifa' }, { key: 'bio', label: 'Bio', type: 'textarea' }, { key: 'image', label: 'Rasm', type: 'image' }],
  projects: [{ key: 'title', label: 'Loyiha nomi', required: true }, { key: 'date', label: 'Sana', type: 'date' }, { key: 'description', label: 'Tavsif', type: 'textarea' }, { key: 'image', label: 'Rasm', type: 'image' }],
  galleryList: [{ key: 'title', label: 'Rasm nomi', required: true }, { key: 'date', label: 'Sana', type: 'date' }, { key: 'description', label: 'Tavsif', type: 'textarea' }, { key: 'image', label: 'Rasm', type: 'image' }],
  videoLessons: [{ key: 'title', label: 'Video nomi', required: true }, { key: 'url', label: 'Video URL', type: 'url', required: true }, { key: 'description', label: 'Tavsif', type: 'textarea' }, { key: 'image', label: 'Muqova', type: 'image' }],
  announcements: [{ key: 'title', label: 'Sarlavha', required: true }, { key: 'date', label: 'Sana', type: 'date' }, { key: 'description', label: 'Matn', type: 'textarea' }, { key: 'image', label: 'Rasm', type: 'image' }],
  birthdays: [{ key: 'name', label: 'Ism-familiya', required: true }, { key: 'date', label: 'Sana', type: 'date', required: true }, { key: 'class', label: 'Sinf / lavozim' }, { key: 'image', label: 'Rasm', type: 'image' }],
  gpaList: [{ key: 'name', label: 'O‘quvchi', required: true }, { key: 'class', label: 'Sinf' }, { key: 'gpa', label: 'GPA', type: 'number', required: true }],
};
const emptyLife: SchoolLifeData = { dormitory: { title: 'Yotoqxona', description: '', image: '', features: [] }, meals: { title: 'Ovqatlanish', description: '', menu: [] }, routine: { title: 'Kun tartibi', description: '', items: [] } };
const uid = () => `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;

async function compressImage(file: File) {
  if (!file.type.startsWith('image/')) throw new Error('Faqat rasm tanlang.');
  if (file.size > 10 * 1024 * 1024) throw new Error('Rasm 10 MB dan kichik bo‘lishi kerak.');
  const bitmap = await createImageBitmap(file);
  const scale = Math.min(1, 1600 / Math.max(bitmap.width, bitmap.height));
  const canvas = document.createElement('canvas');
  canvas.width = Math.max(1, Math.round(bitmap.width * scale));
  canvas.height = Math.max(1, Math.round(bitmap.height * scale));
  const ctx = canvas.getContext('2d');
  if (!ctx) { bitmap.close(); throw new Error('Rasmni qayta ishlashda xatolik.'); }
  ctx.drawImage(bitmap, 0, 0, canvas.width, canvas.height); bitmap.close();
  return canvas.toDataURL('image/jpeg', 0.78);
}

export default function CloudAdminPanelPro({ onClose }: Props) {
  const [session, setSession] = useState<{ user?: { email?: string; app_metadata?: { role?: string } } } | null>(null);
  const [email, setEmail] = useState(''); const [password, setPassword] = useState('');
  const [active, setActive] = useState<Key>('teachers'); const [dashboard, setDashboard] = useState(true);
  const [data, setData] = useState<Record<Key, Item[]>>({ teachers: [], projects: [], galleryList: [], videoLessons: [], announcements: [], birthdays: [], gpaList: [] });
  const [form, setForm] = useState<Item>({}); const [editingId, setEditingId] = useState<string | number | null>(null);
  const [messages, setMessages] = useState<Item[]>([]); const [life, setLife] = useState<SchoolLifeData>(emptyLife);
  const [feature, setFeature] = useState(''); const [meal, setMeal] = useState<Meal>({ name: '', time: '', description: '' }); const [mealId, setMealId] = useState<string | null>(null);
  const [routine, setRoutine] = useState<Routine>({ time: '', activity: '', description: '' }); const [routineId, setRoutineId] = useState<string | null>(null);
  const [coinOpen, setCoinOpen] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const admin = session?.user?.app_metadata?.role === 'admin';

  useEffect(() => {
    supabase.auth.getSession().then(({ data: auth }) => setSession(auth.session as typeof session));
    const { data: listener } = supabase.auth.onAuthStateChange((_event, next) => setSession(next as typeof session));
    return () => listener.subscription.unsubscribe();
  }, []);

  useEffect(() => {
    const next: Item = {}; fields[active].forEach(field => { next[field.key] = field.type === 'date' ? new Date().toISOString().slice(0, 10) : ''; });
    setForm(next); setEditingId(null);
  }, [active]);

  useEffect(() => {
    if (!admin) return;
    let cancelled = false;
    (async () => {
      setBusy(true); setError('');
      try {
        const values = await Promise.all(sections.map(async ({ key }) => [key, await getSiteData(key, [] as Item[])] as const));
        const next = Object.fromEntries(values) as Record<Key, Item[]>;
        const storedLife = await getSiteData('schoolLife', emptyLife);
        const { data: proposalData, error: proposalError } = await supabase.from('student_proposals').select('*').order('created_at', { ascending: false });
        if (proposalError) throw proposalError;
        if (!cancelled) { setData(next); setLife(storedLife || emptyLife); setMessages((proposalData || []) as Item[]); }
      } catch (err) { if (!cancelled) setError(err instanceof Error ? err.message : 'Ma’lumotlar yuklanmadi'); }
      finally { if (!cancelled) setBusy(false); }
    })();
    return () => { cancelled = true; };
  }, [admin]);

  const flash = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(''), 1800); };
  const resetForm = () => { const next: Item = {}; fields[active].forEach(field => { next[field.key] = field.type === 'date' ? new Date().toISOString().slice(0, 10) : ''; }); setForm(next); setEditingId(null); };
  const login = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { const result = await signInAdmin(email.trim(), password); setSession(result.session as typeof session); setPassword(''); } catch (err) { setError(err instanceof Error ? err.message : 'Kirishda xatolik'); } finally { setBusy(false); } };
  const logout = async () => { await signOutAdmin(); setSession(null); };

  const saveItem = async () => {
    for (const field of fields[active]) { const value = String(form[field.key] ?? '').trim(); if (field.required && !value) { setError(`${field.label} maydoni majburiy.`); return; } if (field.type === 'url' && value) { try { new URL(value); } catch { setError('URL noto‘g‘ri.'); return; } } }
    if (active === 'gpaList' && form.gpa !== '' && (Number(form.gpa) < 0 || Number(form.gpa) > 5)) { setError('GPA 0–5 oralig‘ida bo‘lishi kerak.'); return; }
    setBusy(true); setError('');
    try { const item: Item = { ...form, id: editingId ?? uid() }; const next = editingId === null ? [...data[active], item] : data[active].map(row => String(row.id) === String(editingId) ? { ...row, ...item } : row); await saveSiteData(active, next); setData(prev => ({ ...prev, [active]: next })); resetForm(); flash('Saqlandi ✓'); }
    catch (err) { setError(err instanceof Error ? err.message : 'Saqlashda xatolik'); } finally { setBusy(false); }
  };
  const deleteItem = async (rowId: string | number | undefined) => { if (rowId === undefined || !window.confirm('Bu yozuv o‘chirilsinmi?')) return; setBusy(true); try { const next = data[active].filter(row => String(row.id) !== String(rowId)); await saveSiteData(active, next); setData(prev => ({ ...prev, [active]: next })); flash('O‘chirildi ✓'); } catch (err) { setError(err instanceof Error ? err.message : 'O‘chirishda xatolik'); } finally { setBusy(false); } };
  const upload = async (file?: File) => { if (!file) return; setBusy(true); setError(''); try { const image = await compressImage(file); setForm(prev => ({ ...prev, image })); } catch (err) { setError(err instanceof Error ? err.message : 'Rasm yuklanmadi'); } finally { setBusy(false); } };
  const saveLife = async () => { setBusy(true); setError(''); try { await saveSiteData('schoolLife', life); flash('Maktab hayoti saqlandi ✓'); } catch (err) { setError(err instanceof Error ? err.message : 'Maktab hayoti saqlanmadi'); } finally { setBusy(false); } };
  const saveMeal = () => { if (!meal.name.trim() || !meal.time.trim()) { setError('Ovqat nomi va vaqti kerak.'); return; } const next = { ...meal, id: mealId ?? uid() }; setLife(prev => ({ ...prev, meals: { ...prev.meals, menu: mealId ? prev.meals.menu.map(row => row.id === mealId ? next : row) : [...prev.meals.menu, next] } })); setMeal({ name: '', time: '', description: '' }); setMealId(null); };
  const saveRoutine = () => { if (!routine.time.trim() || !routine.activity.trim()) { setError('Vaqt va faoliyat kerak.'); return; } const next = { ...routine, id: routineId ?? uid() }; setLife(prev => ({ ...prev, routine: { ...prev.routine, items: routineId ? prev.routine.items.map(row => row.id === routineId ? next : row) : [...prev.routine.items, next] } })); setRoutine({ time: '', activity: '', description: '' }); setRoutineId(null); };
  const deleteMessage = async (rowId: string | number | undefined) => { if (rowId === undefined || !window.confirm('Murojaat o‘chirilsinmi?')) return; setBusy(true); try { const { error: e } = await supabase.from('student_proposals').delete().eq('id', rowId); if (e) throw e; setMessages(prev => prev.filter(row => String(row.id) !== String(rowId))); } catch (err) { setError(err instanceof Error ? err.message : 'Murojaat o‘chirilmadi'); } finally { setBusy(false); } };

  if (!session || !admin) return <div className="fixed inset-0 z-[100] grid place-items-center bg-slate-950/75 p-4 backdrop-blur-xl"><div className="w-full max-w-md rounded-[28px] bg-white p-7 shadow-2xl"><div className="mb-6 flex items-start justify-between"><div><p className="flex items-center gap-2 text-sm font-bold text-[#0071e3]"><ShieldCheck className="h-4 w-4" /> Secure Admin</p><h2 className="mt-2 text-2xl font-black">School Admin</h2></div><button type="button" onClick={onClose} aria-label="Yopish"><X /></button></div><form onSubmit={login} className="space-y-3"><label className="block text-sm font-semibold">Email<input required type="email" value={email} onChange={e => setEmail(e.target.value)} autoComplete="username" className="mt-1 w-full rounded-2xl border p-3" /></label><label className="block text-sm font-semibold">Parol<input required type="password" value={password} onChange={e => setPassword(e.target.value)} autoComplete="current-password" className="mt-1 w-full rounded-2xl border p-3" /></label>{error && <p role="alert" className="text-sm text-red-600">{error}</p>}<button disabled={busy} className="inline-flex w-full items-center justify-center gap-2 rounded-2xl bg-[#0071e3] py-3 font-semibold text-white disabled:opacity-50"><LogIn className="h-4 w-4" />{busy ? 'Tekshirilmoqda…' : 'Kirish'}</button></form></div></div>;

  const currentFields = fields[active];
  return <div className="fixed inset-0 z-[100] overflow-auto bg-slate-100"><header className="sticky top-0 z-30 border-b bg-white/95 px-4 py-3 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-3"><div><h1 className="font-black">School Admin</h1><p className="text-xs text-slate-500">{session.user?.email}</p></div><div className="flex flex-wrap gap-2"><button type="button" onClick={() => setCoinOpen(true)} className="inline-flex items-center gap-2 rounded-xl bg-amber-50 px-3 py-2 text-sm font-semibold text-amber-700"><Coins className="h-4 w-4" /> SchoolCoin</button><button type="button" onClick={() => window.location.reload()} className="rounded-xl bg-slate-100 p-2" title="Yangilash" aria-label="Yangilash"><RefreshCw className="h-4 w-4" /></button><button type="button" onClick={() => void logout()} className="inline-flex items-center gap-2 rounded-xl bg-slate-900 px-3 py-2 text-sm font-semibold text-white"><LogOut className="h-4 w-4" /> Chiqish</button><button type="button" onClick={onClose} aria-label="Yopish" className="rounded-xl p-2"><X /></button></div></div></header>
  <main className="mx-auto max-w-7xl p-4 md:p-6">{error && <div role="alert" className="mb-4 flex gap-2 rounded-2xl bg-red-50 p-3 text-sm text-red-700"><AlertTriangle className="h-4 w-4" />{error}</div>}{notice && <div role="status" className="mb-4 rounded-2xl bg-emerald-50 p-3 text-sm font-semibold text-emerald-700">{notice}</div>}
  <div className="mb-5 grid grid-cols-2 gap-2 sm:grid-cols-4 lg:grid-cols-8"><button type="button" onClick={() => setDashboard(true)} className={`rounded-2xl border p-3 text-left ${dashboard ? 'border-[#0071e3] bg-blue-50' : 'bg-white'}`}><span className="text-xs text-slate-500">Dashboard</span><span className="mt-1 block text-xl font-black">{sections.reduce((sum, section) => sum + data[section.key].length, 0)}</span></button>{sections.map(section => <button type="button" key={section.key} onClick={() => { setActive(section.key); setDashboard(false); }} className={`rounded-2xl border p-3 text-left ${!dashboard && active === section.key ? 'border-[#0071e3] bg-blue-50' : 'bg-white'}`}><span className="text-xs text-slate-500">{section.label}</span><span className="mt-1 block text-xl font-black">{data[section.key].length}</span></button>)}<button type="button" onClick={() => { setDashboard(false); document.getElementById('school-life-admin')?.scrollIntoView({ behavior: 'smooth' }); }} className="rounded-2xl border bg-white p-3 text-left"><BedDouble className="h-4 w-4 text-[#0071e3]" /><span className="mt-1 block text-xs text-slate-500">Maktab hayoti</span></button></div>
  {dashboard ? <section className="space-y-5"><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">{sections.slice(0, 4).map(section => <button type="button" key={section.key} onClick={() => { setActive(section.key); setDashboard(false); }} className="rounded-3xl bg-white p-5 text-left shadow-sm"><span className="text-xs text-slate-500">{section.label}</span><span className="mt-2 block text-3xl font-black">{data[section.key].length}</span></button>)}</div><div className="rounded-3xl bg-white p-5 shadow-sm"><h2 className="font-black">📨 Murojaatlar · {messages.length}</h2><div className="mt-4 space-y-2">{messages.map(item => <div key={String(item.id)} className="flex items-start justify-between gap-3 rounded-2xl bg-slate-50 p-3"><div><p className="font-semibold">{String(item.full_name || item.name || 'Murojaat')}</p><p className="text-sm text-slate-600">{String(item.title || item.description || item.message || '')}</p></div><button type="button" onClick={() => void deleteMessage(item.id as string | number | undefined)} className="rounded-xl p-2 text-red-600" aria-label="Murojaatni o‘chirish"><Trash2 className="h-4 w-4" /></button></div>)}</div></div></section> : <section className="space-y-5">
  <section className="rounded-3xl bg-white p-5 shadow-sm"><div className="flex items-center justify-between gap-3"><div><h2 className="text-xl font-black">{editingId === null ? `${sections.find(x => x.key === active)?.label} qo‘shish` : 'Tahrirlash'}</h2><p className="text-xs text-slate-500">Create · Read · Update · Delete</p></div><button type="button" onClick={resetForm} className="inline-flex items-center gap-2 rounded-xl border px-3 py-2 text-sm"><Plus className="h-4 w-4" /> Yangi</button></div><div className="mt-5 grid gap-4 md:grid-cols-2">{currentFields.map(field => field.type === 'textarea' ? <label className="text-sm font-semibold md:col-span-2" key={field.key}>{field.label}<textarea rows={4} value={String(form[field.key] ?? '')} onChange={e => setForm(prev => ({ ...prev, [field.key]: e.target.value }))} className="mt-1 w-full rounded-2xl border p-3" /></label> : field.type === 'image' ? <div key={field.key} className="md:col-span-2"><p className="text-sm font-semibold">{field.label}</p><label className="mt-1 inline-flex cursor-pointer items-center gap-2 rounded-2xl border border-dashed px-4 py-3 text-sm"><Upload className="h-4 w-4" /> Rasm tanlash<input type="file" accept="image/*" className="hidden" onChange={e => void upload(e.target.files?.[0])} /></label>{Boolean(form.image) && <img src={String(form.image)} alt="Tanlangan rasm" className="mt-3 h-28 w-40 rounded-xl object-cover" loading="lazy" decoding="async" />}</div> : <label className="text-sm font-semibold" key={field.key}>{field.label}{field.required ? ' *' : ''}<input required={field.required} type={field.type === 'date' || field.type === 'number' || field.type === 'url' ? field.type : 'text'} value={String(form[field.key] ?? '')} onChange={e => setForm(prev => ({ ...prev, [field.key]: field.type === 'number' ? (e.target.value === '' ? '' : Number(e.target.value)) : e.target.value }))} className="mt-1 w-full rounded-2xl border p-3" /></label>)}</div><div className="mt-5 flex flex-wrap gap-2"><button type="button" disabled={busy} onClick={() => void saveItem()} className="inline-flex items-center gap-2 rounded-2xl bg-[#0071e3] px-5 py-3 font-semibold text-white disabled:opacity-50"><Save className="h-4 w-4" /> Saqlash</button>{editingId !== null && <button type="button" onClick={resetForm} className="rounded-2xl border px-5 py-3">Bekor qilish</button>}</div></section>
  <section className="rounded-3xl bg-white p-5 shadow-sm"><h3 className="font-black">{sections.find(x => x.key === active)?.label} · {data[active].length}</h3><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{data[active].map(item => <article key={String(item.id)} className="rounded-2xl border p-4">{Boolean(item.image) && <img src={String(item.image)} alt={String(item.title || item.name || 'Rasm')} loading="lazy" decoding="async" className="mb-3 h-36 w-full rounded-xl object-cover" />}<h4 className="font-bold">{String(item.title || item.name || item.student || 'Ma’lumot')}</h4><p className="mt-1 line-clamp-3 text-sm text-slate-500">{String(item.description || item.bio || item.subject || item.url || (item.gpa !== undefined ? `GPA: ${item.gpa}` : ''))}</p><div className="mt-4 flex gap-2"><button type="button" onClick={() => { setForm({ ...item }); setEditingId(item.id ?? null); }} className="inline-flex items-center gap-1 rounded-xl border px-3 py-2 text-sm"><Pencil className="h-4 w-4" /> Tahrirlash</button><button type="button" disabled={busy} onClick={() => void deleteItem(item.id as string | number | undefined)} className="inline-flex items-center gap-1 rounded-xl border border-red-100 px-3 py-2 text-sm text-red-600"><Trash2 className="h-4 w-4" /> O‘chirish</button></div></article>)}</div></section>
  </section>}
  <section id="school-life-admin" className="mt-5 space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-2xl font-black">🏫 Maktab hayoti</h2><p className="text-sm text-slate-500">Yotoqxona · Ovqatlanish · Kun tartibi</p></div><button type="button" disabled={busy} onClick={() => void saveLife()} className="inline-flex items-center gap-2 rounded-2xl bg-[#0071e3] px-5 py-3 font-semibold text-white"><Save className="h-4 w-4" /> Saqlash</button></div>
  <article className="rounded-3xl bg-white p-5 shadow-sm"><h3 className="font-black">🛏️ Yotoqxona</h3><div className="mt-4 grid gap-3 md:grid-cols-2"><input value={life.dormitory.title} onChange={e => setLife(prev => ({ ...prev, dormitory: { ...prev.dormitory, title: e.target.value } }))} placeholder="Title" className="rounded-2xl border p-3" /><input value={life.dormitory.image} onChange={e => setLife(prev => ({ ...prev, dormitory: { ...prev.dormitory, image: e.target.value } }))} placeholder="Image URL" className="rounded-2xl border p-3" /><textarea value={life.dormitory.description} onChange={e => setLife(prev => ({ ...prev, dormitory: { ...prev.dormitory, description: e.target.value } }))} rows={3} placeholder="Description" className="rounded-2xl border p-3 md:col-span-2" /></div><div className="mt-3 flex gap-2"><input value={feature} onChange={e => setFeature(e.target.value)} placeholder="Feature" className="flex-1 rounded-2xl border p-3" /><button type="button" onClick={() => { if (feature.trim()) { setLife(prev => ({ ...prev, dormitory: { ...prev.dormitory, features: [...prev.dormitory.features, feature.trim()] } })); setFeature(''); } }} className="rounded-2xl bg-slate-900 px-4 text-white" aria-label="Feature qo‘shish"><Plus /></button></div><div className="mt-3 flex flex-wrap gap-2">{life.dormitory.features.map((f, i) => <span key={`${f}-${i}`} className="inline-flex items-center gap-1 rounded-full bg-slate-100 px-3 py-1 text-sm">{f}<button type="button" onClick={() => setLife(prev => ({ ...prev, dormitory: { ...prev.dormitory, features: prev.dormitory.features.filter((_, idx) => idx !== i) } }))} aria-label="Feature o‘chirish"><X className="h-3 w-3" /></button></span>)}</div></article>
  <article className="rounded-3xl bg-white p-5 shadow-sm"><h3 className="font-black">🍽️ Ovqatlanish</h3><div className="mt-4 grid gap-2 md:grid-cols-[1fr_120px_1fr_auto]"><input value={meal.name} onChange={e => setMeal(prev => ({ ...prev, name: e.target.value }))} placeholder="Ovqat nomi" className="rounded-2xl border p-3" /><input value={meal.time} onChange={e => setMeal(prev => ({ ...prev, time: e.target.value }))} placeholder="07:30" className="rounded-2xl border p-3" /><input value={meal.description || ''} onChange={e => setMeal(prev => ({ ...prev, description: e.target.value }))} placeholder="Izoh" className="rounded-2xl border p-3" /><button type="button" onClick={saveMeal} className="rounded-2xl bg-slate-900 px-4 text-white" aria-label="Ovqat saqlash">{mealId ? <Save /> : <Plus />}</button></div><div className="mt-3 space-y-2">{life.meals.menu.map((item, i) => <div key={item.id || i} className="flex flex-wrap items-center justify-between gap-2 rounded-2xl bg-slate-50 p-3"><span><b>{item.name}</b> · {item.time}{item.description ? ` — ${item.description}` : ''}</span><div className="flex gap-1"><button type="button" onClick={() => { setMeal(item); setMealId(item.id || null); }} className="rounded-lg p-2" aria-label="Ovqatni tahrirlash"><Pencil className="h-4 w-4" /></button><button type="button" onClick={() => setLife(prev => ({ ...prev, meals: { ...prev.meals, menu: prev.meals.menu.filter((_, idx) => idx !== i) } }))} className="rounded-lg p-2 text-red-600" aria-label="Ovqatni o‘chirish"><Trash2 className="h-4 w-4" /></button></div></div>)}</div></article>
  <article className="rounded-3xl bg-white p-5 shadow-sm"><h3 className="font-black">🕐 Kun tartibi</h3><div className="mt-4 grid gap-2 md:grid-cols-[120px_1fr_1fr_auto]"><input value={routine.time} onChange={e => setRoutine(prev => ({ ...prev, time: e.target.value }))} placeholder="08:30" className="rounded-2xl border p-3" /><input value={routine.activity} onChange={e => setRoutine(prev => ({ ...prev, activity: e.target.value }))} placeholder="Faoliyat" className="rounded-2xl border p-3" /><input value={routine.description || ''} onChange={e => setRoutine(prev => ({ ...prev, description: e.target.value }))} placeholder="Izoh" className="rounded-2xl border p-3" /><button type="button" onClick={saveRoutine} className="rounded-2xl bg-slate-900 px-4 text-white" aria-label="Kun tartibini saqlash">{routineId ? <Save /> : <Plus />}</button></div><div className="mt-3 space-y-2">{life.routine.items.map((item, i) => <div key={item.id || i} className="flex flex-wrap items-center justify-between gap-2 rounded-2xl bg-slate-50 p-3"><span><b className="text-[#0071e3]">{item.time}</b> · {item.activity}</span><div className="flex gap-1"><button type="button" disabled={i === 0} onClick={() => setLife(prev => { if (i === 0) return prev; const next = [...prev.routine.items]; [next[i - 1], next[i]] = [next[i], next[i - 1]]; return { ...prev, routine: { ...prev.routine, items: next } }; })} className="rounded-lg p-2 disabled:opacity-30" aria-label="Yuqoriga"><ChevronUp className="h-4 w-4" /></button><button type="button" disabled={i === life.routine.items.length - 1} onClick={() => setLife(prev => { if (i === prev.routine.items.length - 1) return prev; const next = [...prev.routine.items]; [next[i], next[i + 1]] = [next[i + 1], next[i]]; return { ...prev, routine: { ...prev.routine, items: next } }; })} className="rounded-lg p-2 disabled:opacity-30" aria-label="Pastga"><ChevronDown className="h-4 w-4" /></button><button type="button" onClick={() => { setRoutine(item); setRoutineId(item.id || null); }} className="rounded-lg p-2" aria-label="Kun tartibini tahrirlash"><Pencil className="h-4 w-4" /></button><button type="button" onClick={() => setLife(prev => ({ ...prev, routine: { ...prev.routine, items: prev.routine.items.filter((_, idx) => idx !== i) } }))} className="rounded-lg p-2 text-red-600" aria-label="Kun tartibini o‘chirish"><Trash2 className="h-4 w-4" /></button></div></div>)}</div></article></section>
  </main>{coinOpen && <SchoolCoinSecure onClose={() => setCoinOpen(false)} initialMode="admin" adminSession={session} />}</div>;
}
