import { FormEvent, useEffect, useState } from 'react';
import { AlertTriangle, BedDouble, ChevronDown, ChevronUp, Coins, LogIn, LogOut, Pencil, Plus, RefreshCw, Save, ShieldCheck, Trash2, Upload, X } from 'lucide-react';
import SchoolCoinSecure from './SchoolCoinSecure';
import { getSiteData, saveSiteData, signInAdmin, signOutAdmin, supabase } from '../lib/supabase';
import { useI18n } from '../i18n';

interface Props { onClose: () => void; }
type Primitive = string | number | boolean | null | undefined;
type Key = 'teachers' | 'projects' | 'galleryList' | 'videoLessons' | 'announcements' | 'birthdays' | 'gpaList';
type Item = Record<string, Primitive> & { id?: string | number };
type Meal = { id?: string; name: string; time: string; description?: string };
type Routine = { id?: string; time: string; activity: string; description?: string };
type SchoolLifeData = { dormitory: { title: string; description: string; image: string; features: string[] }; meals: { title: string; description: string; menu: Meal[] }; routine: { title: string; description: string; items: Routine[] } };

type Field = { key: string; label: string; type?: string; required?: boolean };
const sections: Array<{ key: Key; label: string }> = [
  { key: 'teachers', label: 'admin.section.teachers' }, { key: 'projects', label: 'admin.section.projects' }, { key: 'galleryList', label: 'admin.section.gallery' },
  { key: 'videoLessons', label: 'admin.section.videos' }, { key: 'announcements', label: 'admin.section.announcements' }, { key: 'birthdays', label: 'admin.section.birthdays' }, { key: 'gpaList', label: 'admin.section.gpa' },
];
const fields: Record<Key, Field[]> = {
  teachers: [{ key: 'name', label: 'admin.field.name', required: true }, { key: 'subject', label: 'admin.field.subject', required: true }, { key: 'role', label: 'admin.field.role' }, { key: 'experience', label: 'admin.field.experience' }, { key: 'classes', label: 'admin.field.classes' }, { key: 'category', label: 'admin.field.category' }, { key: 'bio', label: 'admin.field.bio', type: 'textarea' }, { key: 'image', label: 'admin.field.image', type: 'image' }],
  projects: [{ key: 'title', label: 'admin.field.projectTitle', required: true }, { key: 'date', label: 'admin.field.date', type: 'date' }, { key: 'description', label: 'admin.field.description', type: 'textarea' }, { key: 'image', label: 'admin.field.image', type: 'image' }],
  galleryList: [{ key: 'title', label: 'admin.field.galleryTitle', required: true }, { key: 'date', label: 'admin.field.date', type: 'date' }, { key: 'description', label: 'admin.field.description', type: 'textarea' }, { key: 'image', label: 'admin.field.image', type: 'image' }],
  videoLessons: [{ key: 'title', label: 'admin.field.videoTitle', required: true }, { key: 'url', label: 'admin.field.videoUrl', type: 'url', required: true }, { key: 'description', label: 'admin.field.description', type: 'textarea' }, { key: 'image', label: 'admin.field.cover', type: 'image' }],
  announcements: [{ key: 'title', label: 'admin.field.headline', required: true }, { key: 'date', label: 'admin.field.date', type: 'date' }, { key: 'description', label: 'admin.field.text', type: 'textarea' }, { key: 'image', label: 'admin.field.image', type: 'image' }],
  birthdays: [{ key: 'name', label: 'admin.field.name', required: true }, { key: 'date', label: 'admin.field.date', type: 'date', required: true }, { key: 'class', label: 'admin.field.classRole' }, { key: 'image', label: 'admin.field.image', type: 'image' }],
  gpaList: [{ key: 'name', label: 'admin.field.student', required: true }, { key: 'class', label: 'admin.field.classRole' }, { key: 'gpa', label: 'admin.field.gpa', type: 'number', required: true }],
};
const emptyLife: SchoolLifeData = { dormitory: { title: 'Yotoqxona', description: '', image: '', features: [] }, meals: { title: 'Ovqatlanish', description: '', menu: [] }, routine: { title: 'Kun tartibi', description: '', items: [] } };
const uid = () => `${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
const interpolate = (template: string, values: Record<string, string | number>) => Object.entries(values).reduce((result, [key, value]) => result.replaceAll(`{{${key}}}`, String(value)), template);

async function compressImage(file: File, message: (key: string) => string) {
  if (!file.type.startsWith('image/')) throw new Error(message('admin.error.imageOnly'));
  if (file.size > 10 * 1024 * 1024) throw new Error(message('admin.error.imageSize'));
  const bitmap = await createImageBitmap(file);
  const scale = Math.min(1, 1600 / Math.max(bitmap.width, bitmap.height));
  const canvas = document.createElement('canvas');
  canvas.width = Math.max(1, Math.round(bitmap.width * scale));
  canvas.height = Math.max(1, Math.round(bitmap.height * scale));
  const ctx = canvas.getContext('2d');
  if (!ctx) { bitmap.close(); throw new Error(message('admin.error.imageProcess')); }
  ctx.drawImage(bitmap, 0, 0, canvas.width, canvas.height); bitmap.close();
  return canvas.toDataURL('image/jpeg', 0.78);
}

export default function CloudAdminPanelPro({ onClose }: Props) {
  const { t } = useI18n();
  const adminText = (key: string, values?: Record<string, string | number>) => values ? interpolate(t(key), values) : t(key);
  const [session, setSession] = useState<{ user?: { email?: string; app_metadata?: { role?: string } } } | null>(null);
  const [email, setEmail] = useState(''); const [password, setPassword] = useState('');
  const [active, setActive] = useState<Key>('teachers'); const [dashboard, setDashboard] = useState(true);
  const [data, setData] = useState<Record<Key, Item[]>>({ teachers: [], projects: [], galleryList: [], videoLessons: [], announcements: [], birthdays: [], gpaList: [] });
  const [form, setForm] = useState<Item>({}); const [editingId, setEditingId] = useState<string | number | null>(null);
  const [messages, setMessages] = useState<Item[]>([]); const [life, setLife] = useState<SchoolLifeData>(emptyLife);
  const [feature, setFeature] = useState(''); const [meal, setMeal] = useState<Meal>({ name: '', time: '', description: '' }); const [mealId, setMealId] = useState<string | null>(null);
  const [routine, setRoutine] = useState<Routine>({ time: '', activity: '', description: '' }); const [routineId, setRoutineId] = useState<string | null>(null);
  const [coinOpen, setCoinOpen] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const admin = session?.user?.app_metadata?.role === 'admin';

  useEffect(() => {
    supabase.auth.getSession().then(({ data: auth }) => setSession(auth.session as typeof session));
    const { data: listener } = supabase.auth.onAuthStateChange((_event, next) => setSession(next as typeof session));
    return () => listener.subscription.unsubscribe();
  }, []);

  useEffect(() => {
    const next: Item = {}; fields[active].forEach(field => { next[field.key] = field.type === 'date' ? new Date().toISOString().slice(0, 10) : ''; });
    setForm(next); setEditingId(null);
  }, [active]);

  useEffect(() => {
    if (!admin) return;
    let cancelled = false;
    (async () => {
      setBusy(true); setError('');
      try {
        const values = await Promise.all(sections.map(async ({ key }) => [key, await getSiteData(key, [] as Item[])] as const));
        const next = Object.fromEntries(values) as Record<Key, Item[]>;
        const storedLife = await getSiteData('schoolLife', emptyLife);
        const { data: proposalData, error: proposalError } = await supabase.from('student_proposals').select('*').order('created_at', { ascending: false });
        if (proposalError) throw proposalError;
        if (!cancelled) { setData(next); setLife(storedLife || emptyLife); setMessages((proposalData || []) as Item[]); }
      } catch (err) { if (!cancelled) setError(err instanceof Error ? err.message : t('admin.error.dataLoad')); }
      finally { if (!cancelled) setBusy(false); }
    })();
    return () => { cancelled = true; };
  }, [admin, t]);

  const flash = (message: string) => { setNotice(message); window.setTimeout(() => setNotice(''), 1800); };
  const resetForm = () => { const next: Item = {}; fields[active].forEach(field => { next[field.key] = field.type === 'date' ? new Date().toISOString().slice(0, 10) : ''; }); setForm(next); setEditingId(null); };
  const login = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { const result = await signInAdmin(email.trim(), password); setSession(result.session as typeof session); setPassword(''); } catch (err) { setError(err instanceof Error ? err.message : adminText('admin.error.login')); } finally { setBusy(false); } };
  const logout = async () => { await signOutAdmin(); setSession(null); };

  const saveItem = async () => {
    for (const field of fields[active]) { const value = String(form[field.key] ?? '').trim(); if (field.required && !value) { setError(adminText('admin.validation.required', { field: t(field.label) })); return; } if (field.type === 'url' && value) { try { new URL(value); } catch { setError(adminText('admin.validation.invalidUrl')); return; } } }
    if (active === 'gpaList' && form.gpa !== '' && (Number(form.gpa) < 0 || Number(form.gpa) > 5)) { setError(adminText('admin.validation.gpaRange')); return; }
    setBusy(true); setError('');
    try { const item: Item = { ...form, id: editingId ?? uid() }; const next = editingId === null ? [...data[active], item] : data[active].map(row => String(row.id) === String(editingId) ? { ...row, ...item } : row); await saveSiteData(active, next); setData(prev => ({ ...prev, [active]: next })); resetForm(); flash(adminText('admin.feedback.saved')); }
    catch (err) { setError(err instanceof Error ? err.message : adminText('admin.error.save')); } finally { setBusy(false); }
  };
  const deleteItem = async (rowId: string | number | undefined) => { if (rowId === undefined || !window.confirm(adminText('admin.confirm.deleteItem'))) return; setBusy(true); try { const next = data[active].filter(row => String(row.id) !== String(rowId)); await saveSiteData(active, next); setData(prev => ({ ...prev, [active]: next })); flash(adminText('admin.feedback.deleted')); } catch (err) { setError(err instanceof Error ? err.message : adminText('admin.error.delete')); } finally { setBusy(false); } };
  const upload = async (file?: File) => { if (!file) return; setBusy(true); setError(''); try { const image = await compressImage(file, t); setForm(prev => ({ ...prev, image })); } catch (err) { setError(err instanceof Error ? err.message : adminText('admin.error.image')); } finally { setBusy(false); } };
  const saveLife = async () => { setBusy(true); setError(''); try { await saveSiteData('schoolLife', life); flash(adminText('admin.schoolLife.save')); } catch (err) { setError(err instanceof Error ? err.message : adminText('admin.error.schoolLifeSave')); } finally { setBusy(false); } };
  const saveMeal = () => { if (!meal.name.trim() || !meal.time.trim()) { setError(adminText('admin.validation.meal')); return; } const next = { ...meal, id: mealId ?? uid() }; setLife(prev => ({ ...prev, meals: { ...prev.meals, menu: mealId ? prev.meals.menu.map(row => row.id === mealId ? next : row) : [...prev.meals.menu, next] } })); setMeal({ name: '', time: '', description: '' }); setMealId(null); };
  const saveRoutine = () => { if (!routine.time.trim() || !routine.activity.trim()) { setError(adminText('admin.validation.routine')); return; } const next = { ...routine, id: routineId ?? uid() }; setLife(prev => ({ ...prev, routine: { ...prev.routine, items: routineId ? prev.routine.items.map(row => row.id === routineId ? next : row) : [...prev.routine.items, next] } })); setRoutine({ time: '', activity: '', description: '' }); setRoutineId(null); };
  const deleteMessage = async (rowId: string | number | undefined) => { if (rowId === undefined || !window.confirm(adminText('admin.confirm.deleteMessage'))) return; setBusy(true); try { const { error: e } = await supabase.from('student_proposals').delete().eq('id', rowId); if (e) throw e; setMessages(prev => prev.filter(row => String(row.id) !== String(rowId))); } catch (err) { setError(err instanceof Error ? err.message : adminText('admin.error.messageDelete')); } finally { setBusy(false); } };

  if (!session || !admin) return <div className="fixed inset-0 z-[100] grid place-items-center bg-slate-950/75 p-4 backdrop-blur-xl"><div className="w-full max-w-md rounded-[28px] bg-white p-7 shadow-2xl"><div className="mb-6 flex items-start justify-between"><div><p className="flex items-center gap-2 text-sm font-bold text-[#0071e3]"><ShieldCheck className="h-4 w-4" />{adminText('admin.auth.secure')}</p><h2 className="mt-2 text-2xl font-black">{adminText('admin.auth.title')}</h2></div><button type="button" onClick={onClose} aria-label={adminText('admin.common.close')}><X /></button></div><form onSubmit={login} className="space-y-3"><label className="block text-sm font-semibold">{adminText('admin.auth.email')}<input required type="email" value={email} onChange={e => setEmail(e.target.value)} autoComplete="username" className="mt-1 w-full rounded-2xl border p-3" /></label><label className="block text-sm font-semibold">{adminText('admin.auth.password')}<input required type="password" value={password} onChange={e => setPassword(e.target.value)} autoComplete="current-password" className="mt-1 w-full rounded-2xl border p-3" /></label>{error && <p role="alert" className="text-sm text-red-600">{error}</p>}<button disabled={busy} className="inline-flex w-full items-center justify-center gap-2 rounded-2xl bg-[#0071e3] py-3 font-semibold text-white disabled:opacity-50"><LogIn className="h-4 w-4" />{busy ? adminText('admin.auth.checking') : adminText('admin.auth.login')}</button></form></div></div>;

  const currentFields = fields[active];
  return <div className="fixed inset-0 z-[100] overflow-auto bg-slate-100"><header className="sticky top-0 z-30 border-b bg-white/95 px-4 py-3 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-3"><div><h1 className="font-black">{adminText('admin.auth.title')}</h1><p className="text-xs text-slate-500">{session.user?.email}</p></div><div className="flex flex-wrap gap-2"><button type="button" onClick={() => setCoinOpen(true)} className="inline-flex items-center gap-2 rounded-xl bg-amber-50 px-3 py-2 text-sm font-semibold text-amber-700"><Coins className="h-4 w-4" /> {adminText('admin.common.schoolCoin')}</button><button type="button" onClick={() => window.location.reload()} className="rounded-xl bg-slate-100 p-2" title={adminText('admin.common.refresh')} aria-label={adminText('admin.common.refresh')}><RefreshCw className="h-4 w-4" /></button><button type="button" onClick={() => void logout()} className="inline-flex items-center gap-2 rounded-xl bg-slate-900 px-3 py-2 text-sm font-semibold text-white"><LogOut className="h-4 w-4" /> {adminText('admin.common.logout')}</button><button type="button" onClick={onClose} aria-label={adminText('admin.common.close')} className="rounded-xl p-2"><X /></button></div></div></header>
  <main className="mx-auto max-w-7xl p-4 md:p-6">{error && <div role="alert" className="mb-4 flex gap-2 rounded-2xl bg-red-50 p-3 text-sm text-red-700"><AlertTriangle className="h-4 w-4" />{error}</div>}{notice && <div role="status" className="mb-4 rounded-2xl bg-emerald-50 p-3 text-sm font-semibold text-emerald-700">{notice}</div>}
  <div className="mb-5 grid grid-cols-2 gap-2 sm:grid-cols-4 lg:grid-cols-8"><button type="button" onClick={() => setDashboard(true)} className={`rounded-2xl border p-3 text-left ${dashboard ? 'border-[#0071e3] bg-blue-50' : 'bg-white'}`}><span className="text-xs text-slate-500">{adminText('admin.dashboard')}</span><span className="mt-1 block text-xl font-black">{sections.reduce((sum, section) => sum + data[section.key].length, 0)}</span></button>{sections.map(section => <button type="button" key={section.key} onClick={() => { setActive(section.key); setDashboard(false); }} className={`rounded-2xl border p-3 text-left ${!dashboard && active === section.key ? 'border-[#0071e3] bg-blue-50' : 'bg-white'}`}><span className="text-xs text-slate-500">{t(section.label)}</span><span className="mt-1 block text-xl font-black">{data[section.key].length}</span></button>)}<button type="button" onClick={() => { setDashboard(false); document.getElementById('school-life-admin')?.scrollIntoView({ behavior: 'smooth' }); }} className="rounded-2xl border bg-white p-3 text-left"><BedDouble className="h-4 w-4 text-[#0071e3]" /><span className="mt-1 block text-xs text-slate-500">{adminText('admin.schoolLife.title')}</span></button></div>
  {dashboard ? <section className="space-y-5"><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">{sections.slice(0, 4).map(section => <button type="button" key={section.key} onClick={() => { setActive(section.key); setDashboard(false); }} className="rounded-3xl bg-white p-5 text-left shadow-sm"><span className="text-xs text-slate-500">{t(section.label)}</span><span className="mt-2 block text-3xl font-black">{data[section.key].length}</span></button>)}</div><div className="rounded-3xl bg-white p-5 shadow-sm"><h2 className="font-black">📨 {adminText('admin.messages')} · {messages.length}</h2><div className="mt-4 space-y-2">{messages.map(item => <div key={String(item.id)} className="flex items-start justify-between gap-3 rounded-2xl bg-slate-50 p-3"><div><p className="font-semibold">{String(item.full_name || item.name || adminText('admin.data.request'))}</p><p className="text-sm text-slate-600">{String(item.title || item.description || item.message || '')}</p></div><button type="button" onClick={() => void deleteMessage(item.id as string | number | undefined)} className="rounded-xl p-2 text-red-600" aria-label={adminText('admin.message.delete')}><Trash2 className="h-4 w-4" /></button></div>)}</div></div></section> : <section className="space-y-5">
  <section className="rounded-3xl bg-white p-5 shadow-sm"><div className="flex items-center justify-between gap-3"><div><h2 className="text-xl font-black">{editingId === null ? `${t(sections.find(x => x.key === active)?.label ?? '')} ${adminText('admin.form.add').toLowerCase()}` : adminText('admin.form.edit')}</h2><p className="text-xs text-slate-500">{adminText('admin.common.createReadUpdateDelete')}</p></div><button type="button" onClick={resetForm} className="inline-flex items-center gap-2 rounded-xl border px-3 py-2 text-sm"><Plus className="h-4 w-4" /> {adminText('admin.form.new')}</button></div><div className="mt-5 grid gap-4 md:grid-cols-2">{currentFields.map(field => field.type === 'textarea' ? <label className="text-sm font-semibold md:col-span-2" key={field.key}>{t(field.label)}<textarea rows={4} value={String(form[field.key] ?? '')} onChange={e => setForm(prev => ({ ...prev, [field.key]: e.target.value }))} className="mt-1 w-full rounded-2xl border p-3" /></label> : field.type === 'image' ? <div key={field.key} className="md:col-span-2"><p className="text-sm font-semibold">{t(field.label)}</p><label className="mt-1 inline-flex cursor-pointer items-center gap-2 rounded-2xl border border-dashed px-4 py-3 text-sm"><Upload className="h-4 w-4" /> {adminText('admin.form.uploadImage')}<input type="file" accept="image/*" className="hidden" onChange={e => void upload(e.target.files?.[0])} /></label>{Boolean(form.image) && <img src={String(form.image)} alt={adminText('admin.data.image')} className="mt-3 h-28 w-40 rounded-xl object-cover" loading="lazy" decoding="async" />}</div> : <label className="text-sm font-semibold" key={field.key}>{t(field.label)}{field.required ? ` (${adminText('admin.form.required').toLowerCase()})` : ''}<input required={field.required} type={field.type === 'date' || field.type === 'number' || field.type === 'url' ? field.type : 'text'} value={String(form[field.key] ?? '')} onChange={e => setForm(prev => ({ ...prev, [field.key]: field.type === 'number' ? (e.target.value === '' ? '' : Number(e.target.value)) : e.target.value }))} className="mt-1 w-full rounded-2xl border p-3" /></label>)}</div><div className="mt-5 flex flex-wrap gap-2"><button type="button" disabled={busy} onClick={() => void saveItem()} className="inline-flex items-center gap-2 rounded-2xl bg-[#0071e3] px-5 py-3 font-semibold text-white disabled:opacity-50"><Save className="h-4 w-4" /> {adminText('admin.form.save')}</button>{editingId !== null && <button type="button" onClick={resetForm} className="rounded-2xl border px-5 py-3">{adminText('admin.form.cancel')}</button>}</div></section>
  <section className="rounded-3xl bg-white p-5 shadow-sm"><h3 className="font-black">{t(sections.find(x => x.key === active)?.label ?? '')} · {data[active].length}</h3><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{data[active].map(item => <article key={String(item.id)} className="rounded-2xl border p-4">{Boolean(item.image) && <img src={String(item.image)} alt={String(item.title || item.name || adminText('admin.data.image'))} loading="lazy" decoding="async" className="mb-3 h-36 w-full rounded-xl object-cover" />}<h4 className="font-bold">{String(item.title || item.name || item.student || adminText('admin.data.information'))}</h4><p className="mt-1 line-clamp-3 text-sm text-slate-500">{String(item.description || item.bio || item.subject || item.url || (item.gpa !== undefined ? adminText('admin.item.gpa', { value: item.gpa }) : ''))}</p><div className="mt-4 flex gap-2"><button type="button" onClick={() => { setForm({ ...item }); setEditingId(item.id ?? null); }} className="inline-flex items-center gap-1 rounded-xl border px-3 py-2 text-sm"><Pencil className="h-4 w-4" /> {adminText('admin.form.edit')}</button><button type="button" disabled={busy} onClick={() => void deleteItem(item.id as string | number | undefined)} className="inline-flex items-center gap-1 rounded-xl border border-red-100 px-3 py-2 text-sm text-red-600"><Trash2 className="h-4 w-4" /> {t('delete')}</button></div></article>)}</div></section>
  </section>}
  <section id="school-life-admin" className="mt-5 space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-2xl font-black">🏫 {adminText('admin.schoolLife.title')}</h2><p className="text-sm text-slate-500">{adminText('admin.schoolLife.subtitle')}</p></div><button type="button" disabled={busy} onClick={() => void saveLife()} className="inline-flex items-center gap-2 rounded-2xl bg-[#0071e3] px-5 py-3 font-semibold text-white"><Save className="h-4 w-4" /> {adminText('admin.form.save')}</button></div>
  <article className="rounded-3xl bg-white p-5 shadow-sm"><h3 className="font-black">🛏️ {adminText('admin.schoolLife.dormitory')}</h3><div className="mt-4 grid gap-3 md:grid-cols-2"><input value={life.dormitory.title} onChange={e => setLife(prev => ({ ...prev, dormitory: { ...prev.dormitory, title: e.target.value } }))} placeholder={adminText('admin.schoolLife.titlePlaceholder')} className="rounded-2xl border p-3" /><input value={life.dormitory.image} onChange={e => setLife(prev => ({ ...prev, dormitory: { ...prev.dormitory, image: e.target.value } }))} placeholder={adminText('admin.schoolLife.imageUrl')} className="rounded-2xl border p-3" /><textarea value={life.dormitory.description} onChange={e => setLife(prev => ({ ...prev, dormitory: { ...prev.dormitory, description: e.target.value } }))} rows={3} placeholder={adminText('admin.schoolLife.descriptionPlaceholder')} className="rounded-2xl border p-3 md:col-span-2" /></div><div className="mt-3 flex gap-2"><input value={feature} onChange={e => setFeature(e.target.value)} placeholder={adminText('admin.schoolLife.feature')} className="flex-1 rounded-2xl border p-3" /><button type="button" onClick={() => { if (feature.trim()) { setLife(prev => ({ ...prev, dormitory: { ...prev.dormitory, features: [...prev.dormitory.features, feature.trim()] } })); setFeature(''); } }} className="rounded-2xl bg-slate-900 px-4 text-white" aria-label={adminText('admin.schoolLife.addFeature')}><Plus /></button></div><div className="mt-3 flex flex-wrap gap-2">{life.dormitory.features.map((f, i) => <span key={`${f}-${i}`} className="inline-flex items-center gap-1 rounded-full bg-slate-100 px-3 py-1 text-sm">{f}<button type="button" onClick={() => setLife(prev => ({ ...prev, dormitory: { ...prev.dormitory, features: prev.dormitory.features.filter((_, idx) => idx !== i) } }))} aria-label={adminText('admin.schoolLife.removeFeature')}><X className="h-3 w-3" /></button></span>)}</div></article>
  <article className="rounded-3xl bg-white p-5 shadow-sm"><h3 className="font-black">🍽️ {adminText('admin.schoolLife.meals')}</h3><div className="mt-4 grid gap-2 md:grid-cols-[1fr_120px_1fr_auto]"><input value={meal.name} onChange={e => setMeal(prev => ({ ...prev, name: e.target.value }))} placeholder={adminText('admin.schoolLife.mealName')} className="rounded-2xl border p-3" /><input value={meal.time} onChange={e => setMeal(prev => ({ ...prev, time: e.target.value }))} placeholder={adminText('admin.schoolLife.mealTime')} className="rounded-2xl border p-3" /><input value={meal.description || ''} onChange={e => setMeal(prev => ({ ...prev, description: e.target.value }))} placeholder={adminText('admin.schoolLife.mealNote')} className="rounded-2xl border p-3" /><button type="button" onClick={saveMeal} className="rounded-2xl bg-slate-900 px-4 text-white" aria-label={mealId ? adminText('admin.schoolLife.editMeal') : adminText('admin.schoolLife.saveMeal')}>{mealId ? <Save /> : <Plus />}</button></div><div className="mt-3 space-y-2">{life.meals.menu.map((item, i) => <div key={item.id || i} className="flex flex-wrap items-center justify-between gap-2 rounded-2xl bg-slate-50 p-3"><span><b>{item.name}</b> · {item.time}{item.description ? ` — ${item.description}` : ''}</span><div className="flex gap-1"><button type="button" onClick={() => { setMeal(item); setMealId(item.id || null); }} className="rounded-lg p-2" aria-label={adminText('admin.schoolLife.editMeal')}><Pencil className="h-4 w-4" /></button><button type="button" onClick={() => setLife(prev => ({ ...prev, meals: { ...prev.meals, menu: prev.meals.menu.filter((_, idx) => idx !== i) } }))} className="rounded-lg p-2 text-red-600" aria-label={adminText('admin.schoolLife.deleteMeal')}><Trash2 className="h-4 w-4" /></button></div></div>)}</div></article>
  <article className="rounded-3xl bg-white p-5 shadow-sm"><h3 className="font-black">🕐 {adminText('admin.schoolLife.routine')}</h3><div className="mt-4 grid gap-2 md:grid-cols-[120px_1fr_1fr_auto]"><input value={routine.time} onChange={e => setRoutine(prev => ({ ...prev, time: e.target.value }))} placeholder={adminText('admin.schoolLife.routineTime')} className="rounded-2xl border p-3" /><input value={routine.activity} onChange={e => setRoutine(prev => ({ ...prev, activity: e.target.value }))} placeholder={adminText('admin.schoolLife.activity')} className="rounded-2xl border p-3" /><input value={routine.description || ''} onChange={e => setRoutine(prev => ({ ...prev, description: e.target.value }))} placeholder={adminText('admin.schoolLife.routineNote')} className="rounded-2xl border p-3" /><button type="button" onClick={saveRoutine} className="rounded-2xl bg-slate-900 px-4 text-white" aria-label={routineId ? adminText('admin.schoolLife.editRoutine') : adminText('admin.schoolLife.routine')} >{routineId ? <Save /> : <Plus />}</button></div><div className="mt-3 space-y-2">{life.routine.items.map((item, i) => <div key={item.id || i} className="flex flex-wrap items-center justify-between gap-2 rounded-2xl bg-slate-50 p-3"><span><b className="text-[#0071e3]">{item.time}</b> · {item.activity}</span><div className="flex gap-1"><button type="button" disabled={i === 0} onClick={() => setLife(prev => { if (i === 0) return prev; const next = [...prev.routine.items]; [next[i - 1], next[i]] = [next[i], next[i - 1]]; return { ...prev, routine: { ...prev.routine, items: next } }; })} className="rounded-lg p-2 disabled:opacity-30" aria-label={adminText('admin.schoolLife.moveUp')}><ChevronUp className="h-4 w-4" /></button><button type="button" disabled={i === life.routine.items.length - 1} onClick={() => setLife(prev => { if (i === prev.routine.items.length - 1) return prev; const next = [...prev.routine.items]; [next[i], next[i + 1]] = [next[i + 1], next[i]]; return { ...prev, routine: { ...prev.routine, items: next }; })} className="rounded-lg p-2 disabled:opacity-30" aria-label={adminText('admin.schoolLife.moveDown')}><ChevronDown className="h-4 w-4" /></button><button type="button" onClick={() => { setRoutine(item); setRoutineId(item.id || null); }} className="rounded-lg p-2" aria-label={adminText('admin.schoolLife.editRoutine')}><Pencil className="h-4 w-4" /></button><button type="button" onClick={() => setLife(prev => ({ ...prev, routine: { ...prev.routine, items: prev.routine.items.filter((_, idx) => idx !== i) } }))} className="rounded-lg p-2 text-red-600" aria-label={adminText('admin.schoolLife.deleteRoutine')}><Trash2 className="h-4 w-4" /></button></div></div>)}</div></article></section>
  </main>{coinOpen && <SchoolCoinSecure onClose={() => setCoinOpen(false)} initialMode="admin" adminSession={session} />}</div>;
}
