import { useEffect, useState } from 'react';
import { ArrowUpRight, CalendarDays, Megaphone } from 'lucide-react';
import { getSiteData } from '../lib/supabase';
import { useI18n } from '../i18n';

type NewsItem = { id?: string | number; title?: string; content?: string; description?: string; message?: string; date?: string; category?: string; image?: string; thumbnail?: string };
export default function News() {
  const { t } = useI18n(); const [items, setItems] = useState<NewsItem[]>([]); const [state, setState] = useState<'loading'|'success'|'empty'|'error'>('loading');
  useEffect(() => { let alive = true; getSiteData<NewsItem[]>('announcements', []).then(data => { if (!alive) return; setItems(Array.isArray(data) ? data : []); setState(Array.isArray(data) && data.length ? 'success' : 'empty'); }).catch(() => alive && setState('error')); return () => { alive = false; }; }, []);
  const latest = [...items].sort((a,b) => String(b.date||'').localeCompare(String(a.date||''))).slice(0,6);
  return <section id="news" className="scroll-mt-24 px-5 py-10 sm:px-8 lg:px-12 lg:py-16"><div className="mx-auto max-w-7xl"><div className="mb-8 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-blue-600">{t('news')}</p><h2 className="mt-2 text-3xl font-black tracking-tight text-slate-950 dark:text-white sm:text-4xl">{t('newsFromSchool')}</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-600 dark:text-slate-400">{t('newsEmptyHint')}</p></div><span className="inline-flex w-fit items-center gap-2 rounded-full border border-slate-200 bg-white/80 px-3 py-2 text-xs font-semibold text-slate-600 dark:border-white/10 dark:bg-slate-900/80 dark:text-slate-300"><Megaphone className="h-4 w-4 text-blue-600" /> {t('officialSource')}</span></div>
    {state==='loading' && <div className="grid gap-4 md:grid-cols-3">{[1,2,3].map(i=><div key={i} className="h-44 animate-pulse rounded-3xl border border-slate-200 bg-white/70 dark:border-white/10 dark:bg-slate-900/70" />)}</div>}
    {state==='error' && <div role="alert" className="rounded-3xl border border-red-200 bg-red-50 p-6 text-sm text-red-700 dark:border-red-500/20 dark:bg-red-950/30 dark:text-red-300">{t('newsError')}</div>}
    {state==='empty' && <div className="rounded-3xl border border-dashed border-slate-300 bg-white/60 p-10 text-center dark:border-white/10 dark:bg-slate-900/60"><Megaphone className="mx-auto h-8 w-8 text-slate-400" /><p className="mt-3 font-semibold text-slate-700 dark:text-slate-200">{t('newsEmpty')}</p><p className="mt-1 text-sm text-slate-500">{t('newsEmptyHint')}</p></div>}
    {state==='success' && <div className="grid gap-5 lg:grid-cols-[1.35fr_.65fr]"><article className="group overflow-hidden rounded-[28px] border border-slate-200 bg-white shadow-sm dark:border-white/10 dark:bg-slate-900"><>{(latest[0].image||latest[0].thumbnail)&&<img src={latest[0].image||latest[0].thumbnail} alt="" className="h-56 w-full object-cover" loading="lazy" />}</><div className="p-6"><div className="flex items-center gap-2 text-xs text-slate-500"><CalendarDays className="h-4 w-4" />{latest[0].date||t('dateUnavailable')}</div><h3 className="mt-3 text-2xl font-black text-slate-950 dark:text-white">{latest[0].title||t('news')}</h3><p className="mt-3 text-sm leading-6 text-slate-600 dark:text-slate-300">{latest[0].content||latest[0].description||latest[0].message||t('noDetails')}</p></div></article><div className="space-y-3">{latest.slice(1).map((item,index)=><article key={item.id??`${item.title}-${index}`} className="rounded-2xl border border-slate-200 bg-white/85 p-5 dark:border-white/10 dark:bg-slate-900/85"><div className="flex items-start justify-between gap-3"><div><p className="text-[11px] font-bold uppercase tracking-[.14em] text-blue-600">{item.category||t('news')}</p><h3 className="mt-1 font-bold text-slate-900 dark:text-white">{item.title||t('news')}</h3><p className="mt-2 line-clamp-2 text-sm text-slate-600 dark:text-slate-300">{item.content||item.description||item.message||t('noDetails')}</p></div><ArrowUpRight className="mt-1 h-4 w-4 shrink-0 text-slate-400" /></div><p className="mt-3 text-xs text-slate-400">{item.date||t('dateUnavailable')}</p></article>)}</div></div>}
  </div></section>;
}
