import { FormEvent, useEffect, useMemo, useState } from 'react';
import { ArrowRight, BookOpen, Building2, CalendarDays, CheckCircle2, Clock3, GalleryHorizontal, HeartHandshake, ImageOff, Lightbulb, MapPin, Megaphone, PlayCircle, Send, ShieldCheck, Sparkles, Trophy, Users } from 'lucide-react';
import { administration, stats, subjects } from '../lib/data';
import { getSiteData, supabase, supabaseConfigured } from '../lib/supabase';
import { Locale, useSitePreferences } from '../lib/site-preferences';

type PublishedItem = { id?: string | number; title?: string; content?: string; description?: string; message?: string; date?: string; category?: string; time?: string; location?: string; year?: string; result?: string };

const copy = {
  uz: {
    heroEyebrow: '1-IMI Jizzax · ixtisoslashtirilgan maktab-internati', heroTitle: 'Bilim, innovatsiya va yetakchilik uchun makon.', heroText: 'Jizzax shahridagi 1-sonli ixtisoslashtirilgan maktab-internatining rasmiy raqamli portali.', exploreSchool: 'Maktab haqida', academicPortal: 'Akademik portal', dataNote: 'Ko‘rsatkichlar maktab ma’muriyati tomonidan tasdiqlanishi kutilmoqda.',
    schoolEyebrow: 'Maktab', schoolTitle: 'Maktabimiz haqida', schoolText: 'Ixtisoslashtirilgan ta’lim va internat hayotini birlashtirgan maktab hamjamiyati.', history: 'Tarix', mission: 'Missiya va qadriyatlar', leadership: 'Rahbariyat', teachers: 'O‘qituvchilar', facilities: 'Infratuzilma va laboratoriyalar', historyText: 'Tarixiy ma’lumotlar rasmiy manba bilan tekshirilmoqda.', missionText: 'Har bir o‘quvchining akademik, ijtimoiy va yetakchilik salohiyatini rivojlantirish.', facilityText: 'Maktab infratuzilmasi haqidagi batafsil ma’lumotlar rasmiy nashr uchun tayyorlanmoqda.', review: 'Ko‘rib chiqilmoqda',
    educationEyebrow: 'Ta’lim', educationTitle: 'Akademik portal', educationText: 'Fanlar, o‘qituvchilar, jadval, GPA va o‘quv resurslari uchun yagona bo‘lim.', subjects: 'Fanlar', schedule: 'Dars jadvali', gpa: 'GPA / reyting', olympiads: 'Olimpiadalar va tanlovlar', resources: 'O‘quv resurslari', videos: 'Video darslar', portalEmpty: 'Rasmiy akademik ma’lumotlar nashr etilishi bilan shu yerda ko‘rinadi.', videoEmpty: 'Hozircha tekshirilgan video darslar nashr etilmagan.',
    lifeEyebrow: 'Maktab hayoti', lifeTitle: 'Internatdagi kundalik hayot', lifeText: 'Yashash, ovqatlanish, o‘qish va bo‘sh vaqt muvozanatini qo‘llab-quvvatlashga qaratilgan bo‘lim.', dormitory: 'Yotoqxona', meals: 'Ovqatlanish', daily: 'Kun tartibi', sport: 'Sport', clubs: 'To‘garaklar va klublar', events: 'Tadbirlar', studentLife: 'O‘quvchilar hayoti', president: 'Prezident devoni', lifeEmpty: 'Bu bo‘limning rasmiy tafsilotlari ma’muriyat tomonidan yangilanadi.',
    newsEyebrow: 'Yangiliklar', newsTitle: 'Rasmiy yangiliklar', newsText: 'Faqat maktab ma’muriyati e’lon qilgan ma’lumotlar ko‘rsatiladi.', newsEmpty: 'Hozircha rasmiy yangiliklar e’lon qilinmagan.', eventsTitle: 'Yaqin tadbirlar', eventsEmpty: 'Hozircha yaqin tadbirlar e’lon qilinmagan.', achievementsTitle: 'Yutuqlar', achievementsEmpty: 'Tasdiqlangan yutuqlar nashr etilganda shu yerda ko‘rinadi.',
    moreEyebrow: 'Media va hamjamiyat', moreTitle: 'Yutuqlar, innovatsiya va media', innovation: 'Innovatsiya', innovationText: 'STEM, robototexnika va o‘quvchi loyihalari haqidagi tasdiqlangan xabarlar shu bo‘limda nashr etiladi.', gallery: 'Galereya', galleryEmpty: 'Hozircha tekshirilgan maktab galereyasi mavjud emas.', media: 'Media', mediaText: 'Rasmiy media materiallari admin tomonidan boshqariladi.',
    contactEyebrow: 'Aloqa', contactTitle: 'Murojaat yuboring', contactText: 'Savol yoki taklifingizni yuboring. U faqat ruxsatli ma’muriyat foydalanuvchilariga ko‘rinadi.', contactReview: 'Telefon, manzil va ijtimoiy tarmoq ma’lumotlarida ziddiyatlar bor; ular rasmiy tasdiqdan keyin e’lon qilinadi.', name: 'Ismingiz (ixtiyoriy)', message: 'Murojaatingiz', send: 'Yuborish', sending: 'Yuborilmoqda…', sent: 'Murojaatingiz yuborildi.', sendError: 'Murojaatni yuborib bo‘lmadi. Iltimos, keyinroq urinib ko‘ring.', unavailable: 'Murojaat xizmati hozir sozlanmagan.', footer: '1-IMI Jizzax rasmiy raqamli portali.', rights: 'Barcha huquqlar himoyalangan.', learnMore: 'Batafsil', loading: 'Yuklanmoqda…', languageContent: 'Sayt interfeysi tanlangan tilda ko‘rsatiladi. Admin nashrlari asl tilida saqlanadi.',
  },
  ru: {
    heroEyebrow: '1-ИМИ Джизак · специализированная школа-интернат', heroTitle: 'Пространство для знаний, инноваций и лидерства.', heroText: 'Официальный цифровой портал специализированной школы-интерната №1 города Джизака.', exploreSchool: 'О школе', academicPortal: 'Академический портал', dataNote: 'Показатели ожидают подтверждения администрацией школы.',
    schoolEyebrow: 'Школа', schoolTitle: 'О нашей школе', schoolText: 'Школьное сообщество, объединяющее специализированное обучение и жизнь в интернате.', history: 'История', mission: 'Миссия и ценности', leadership: 'Руководство', teachers: 'Учителя', facilities: 'Инфраструктура и лаборатории', historyText: 'Исторические сведения проходят проверку по официальному источнику.', missionText: 'Развивать академический, социальный и лидерский потенциал каждого ученика.', facilityText: 'Подробные сведения об инфраструктуре готовятся к официальной публикации.', review: 'На проверке',
    educationEyebrow: 'Обучение', educationTitle: 'Академический портал', educationText: 'Единый раздел для предметов, учителей, расписания, GPA и учебных ресурсов.', subjects: 'Предметы', schedule: 'Расписание', gpa: 'GPA / рейтинг', olympiads: 'Олимпиады и конкурсы', resources: 'Учебные ресурсы', videos: 'Видеоуроки', portalEmpty: 'Официальная академическая информация появится здесь после публикации.', videoEmpty: 'Проверенные видеоуроки пока не опубликованы.',
    lifeEyebrow: 'Школьная жизнь', lifeTitle: 'Повседневная жизнь в интернате', lifeText: 'Раздел о балансе проживания, питания, учёбы и свободного времени.', dormitory: 'Общежитие', meals: 'Питание', daily: 'Распорядок дня', sport: 'Спорт', clubs: 'Кружки и клубы', events: 'События', studentLife: 'Жизнь учеников', president: 'Совет президента', lifeEmpty: 'Официальные детали этого раздела обновляются администрацией.',
    newsEyebrow: 'Новости', newsTitle: 'Официальные новости', newsText: 'Здесь показываются только объявления, опубликованные администрацией школы.', newsEmpty: 'Официальных новостей пока нет.', eventsTitle: 'Ближайшие события', eventsEmpty: 'Ближайшие события пока не опубликованы.', achievementsTitle: 'Достижения', achievementsEmpty: 'Подтверждённые достижения появятся здесь после публикации.',
    moreEyebrow: 'Медиа и сообщество', moreTitle: 'Достижения, инновации и медиа', innovation: 'Инновации', innovationText: 'Подтверждённые новости о STEM, робототехнике и ученических проектах публикуются в этом разделе.', gallery: 'Галерея', galleryEmpty: 'Проверенная школьная галерея пока недоступна.', media: 'Медиа', mediaText: 'Официальные медиаматериалы управляются администратором.',
    contactEyebrow: 'Контакты', contactTitle: 'Отправьте обращение', contactText: 'Отправьте вопрос или предложение. Его увидят только авторизованные сотрудники администрации.', contactReview: 'В телефонах, адресах и ссылках на соцсети есть расхождения; они будут опубликованы после официального подтверждения.', name: 'Ваше имя (необязательно)', message: 'Ваше обращение', send: 'Отправить', sending: 'Отправка…', sent: 'Ваше обращение отправлено.', sendError: 'Не удалось отправить обращение. Повторите попытку позже.', unavailable: 'Сервис обращений пока не настроен.', footer: 'Официальный цифровой портал 1-ИМИ Джизак.', rights: 'Все права защищены.', learnMore: 'Подробнее', loading: 'Загрузка…', languageContent: 'Интерфейс сайта отображается на выбранном языке. Публикации администрации сохраняются на исходном языке.',
  },
  en: {
    heroEyebrow: '1-IMI Jizzakh · specialised boarding school', heroTitle: 'A place for learning, innovation, and leadership.', heroText: 'The official digital portal of Jizzakh City Specialised Boarding School No. 1.', exploreSchool: 'About the school', academicPortal: 'Academic portal', dataNote: 'These figures await confirmation by the school administration.',
    schoolEyebrow: 'School', schoolTitle: 'About our school', schoolText: 'A school community that brings together specialised education and boarding life.', history: 'History', mission: 'Mission and values', leadership: 'Leadership', teachers: 'Teachers', facilities: 'Facilities and laboratories', historyText: 'Historical information is being checked against an official source.', missionText: 'To develop every learner’s academic, social, and leadership potential.', facilityText: 'Detailed facilities information is being prepared for official publication.', review: 'Under review',
    educationEyebrow: 'Education', educationTitle: 'Academic portal', educationText: 'One place for subjects, teachers, timetable, GPA, and learning resources.', subjects: 'Subjects', schedule: 'Timetable', gpa: 'GPA / ranking', olympiads: 'Olympiads and competitions', resources: 'Learning resources', videos: 'Video lessons', portalEmpty: 'Official academic information will appear here once published.', videoEmpty: 'No verified video lessons have been published yet.',
    lifeEyebrow: 'School life', lifeTitle: 'Daily boarding life', lifeText: 'A section for the balance of living, meals, learning, and recreation.', dormitory: 'Dormitory', meals: 'Meals', daily: 'Daily routine', sport: 'Sport', clubs: 'Clubs and societies', events: 'Events', studentLife: 'Student life', president: 'Student president office', lifeEmpty: 'Official details for this section are updated by the administration.',
    newsEyebrow: 'News', newsTitle: 'Official news', newsText: 'Only announcements published by the school administration appear here.', newsEmpty: 'No official news have been published yet.', eventsTitle: 'Upcoming events', eventsEmpty: 'No upcoming events have been published yet.', achievementsTitle: 'Achievements', achievementsEmpty: 'Verified achievements will appear here when published.',
    moreEyebrow: 'Media and community', moreTitle: 'Achievements, innovation, and media', innovation: 'Innovation', innovationText: 'Verified news about STEM, robotics, and student projects will be published in this section.', gallery: 'Gallery', galleryEmpty: 'No verified school gallery is available yet.', media: 'Media', mediaText: 'Official media materials are managed by an administrator.',
    contactEyebrow: 'Contact', contactTitle: 'Send an enquiry', contactText: 'Send a question or suggestion. It will only be visible to authorised school staff.', contactReview: 'Phone numbers, address details, and social links conflict in the repository; they will be published after official confirmation.', name: 'Your name (optional)', message: 'Your message', send: 'Send', sending: 'Sending…', sent: 'Your enquiry has been sent.', sendError: 'Your enquiry could not be sent. Please try again later.', unavailable: 'The enquiry service is not configured.', footer: 'The official digital portal of 1-IMI Jizzakh.', rights: 'All rights reserved.', learnMore: 'Learn more', loading: 'Loading…', languageContent: 'The site interface is shown in the selected language. Administration publications remain in their source language.',
  },
} as const;

const statLabels: Record<Locale, string[]> = { uz: ['O‘quvchilar', 'O‘qituvchilar', 'Chuqurlashtirilgan fanlar', 'Yutuqlar (2024)', 'Birinchi bitiruvchilar', 'OTMga kirish'], ru: ['Ученики', 'Учителя', 'Углублённые предметы', 'Достижения (2024)', 'Первые выпускники', 'Поступление в вузы'], en: ['Students', 'Teachers', 'Specialised subjects', 'Achievements (2024)', 'First graduates', 'University admission'] };
const roles: Record<Locale, string[]> = { uz: ['Maktab direktori', 'Direktor o‘rinbosari', 'Direktor o‘rinbosari', 'Maktab maslahatchisi'], ru: ['Директор школы', 'Заместитель директора', 'Заместитель директора', 'Советник школы'], en: ['School principal', 'Deputy principal', 'Deputy principal', 'School adviser'] };
const subjectNames: Record<Locale, Record<string, string>> = { uz: { Mathematics: 'Matematika', Physics: 'Fizika', Informatics: 'Informatika', English: 'Ingliz tili', Biology: 'Biologiya', Chemistry: 'Kimyo' }, ru: { Mathematics: 'Математика', Physics: 'Физика', Informatics: 'Информатика', English: 'Английский язык', Biology: 'Биология', Chemistry: 'Химия' }, en: { Mathematics: 'Mathematics', Physics: 'Physics', Informatics: 'Computer science', English: 'English', Biology: 'Biology', Chemistry: 'Chemistry' } };

function SectionHeader({ eyebrow, title, text }: { eyebrow: string; title: string; text: string }) { return <div className="mx-auto max-w-3xl text-center"><p className="site-eyebrow">{eyebrow}</p><h2 className="site-heading mt-3">{title}</h2><p className="site-muted mx-auto mt-4 max-w-2xl">{text}</p></div>; }
function EmptyState({ children }: { children: React.ReactNode }) { return <div className="site-empty"><ImageOff className="mx-auto h-7 w-7" /><p className="mt-3">{children}</p></div>; }
function Card({ icon: Icon, title, children }: { icon?: typeof Building2; title: string; children: React.ReactNode }) { return <article className="site-card">{Icon && <Icon className="h-6 w-6 text-[#0071e3]" />}<h3 className="mt-4 text-lg font-bold">{title}</h3><div className="site-muted mt-2 text-sm leading-6">{children}</div></article>; }

export default function PublicSite({ announcements }: { announcements: PublishedItem[] }) {
  const { locale } = useSitePreferences();
  const text = copy[locale];
  const [events, setEvents] = useState<PublishedItem[] | null>(null);
  const [achievements, setAchievements] = useState<PublishedItem[] | null>(null);
  const [form, setForm] = useState({ name: '', message: '' });
  const [formState, setFormState] = useState<'idle' | 'sending' | 'sent' | 'error'>('idle');
  const publicSubjects = useMemo(() => subjects.map((subject: { name?: string }) => subjectNames[locale][subject.name ?? ''] ?? subject.name ?? ''), [locale]);

  useEffect(() => { let alive = true; if (!supabaseConfigured) { setEvents([]); setAchievements([]); return; } Promise.all([getSiteData<PublishedItem[]>('events', []), getSiteData<PublishedItem[]>('achievements', [])]).then(([nextEvents, nextAchievements]) => { if (alive) { setEvents(nextEvents); setAchievements(nextAchievements); } }).catch(() => { if (alive) { setEvents([]); setAchievements([]); } }); return () => { alive = false; }; }, []);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!form.message.trim() || formState === 'sending') return; if (!supabaseConfigured) { setFormState('error'); return; } setFormState('sending'); const { error } = await supabase.from('student_proposals').insert({ ministry: 'Public website enquiry', full_name: form.name.trim() || 'Anonymous visitor', class: 'Website visitor', title: 'Website enquiry', description: form.message.trim(), status: 'pending' }); if (error) { setFormState('error'); return; } setForm({ name: '', message: '' }); setFormState('sent'); };

  return <main className="site-main">
    <section id="hero" className="site-hero"><div className="site-wrap py-28 sm:py-36"><div className="max-w-3xl"><p className="site-eyebrow">{text.heroEyebrow}</p><h1 className="mt-5 text-4xl font-black tracking-tight sm:text-6xl">{text.heroTitle}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600 dark:text-slate-300">{text.heroText}</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><a className="site-primary" href="#about">{text.exploreSchool}<ArrowRight className="h-4 w-4" /></a><a className="site-secondary" href="#academic">{text.academicPortal}</a></div></div><div className="mt-16 grid grid-cols-2 gap-3 lg:grid-cols-6">{stats.map((stat, index) => <div key={stat.label} className="site-stat"><strong>{stat.value.toLocaleString()}{stat.suffix}</strong><span>{statLabels[locale][index]}</span></div>)}</div><p className="mt-4 text-xs text-slate-500 dark:text-slate-400">{text.dataNote}</p></div></section>

    <section id="about" className="site-section"><div className="site-wrap"><SectionHeader eyebrow={text.schoolEyebrow} title={text.schoolTitle} text={text.schoolText} /><div className="mt-10 grid gap-4 md:grid-cols-3"><Card icon={Clock3} title={text.history}>{text.historyText}</Card><Card icon={HeartHandshake} title={text.mission}>{text.missionText}</Card><Card icon={Building2} title={text.facilities}>{text.facilityText}</Card></div></div></section>
    <section id="administration" className="site-section site-tint"><div className="site-wrap"><SectionHeader eyebrow={text.schoolEyebrow} title={text.leadership} text={text.languageContent} /><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{administration.slice(0, 4).map((person, index) => <article key={person.id} className="site-card overflow-hidden p-0"><img src={person.image} alt={person.name} loading="lazy" className="h-48 w-full object-cover" /><div className="p-5"><h3 className="font-bold">{person.name}</h3><p className="site-muted mt-1 text-sm">{roles[locale][index]}</p><span className="mt-3 inline-block text-xs text-amber-700 dark:text-amber-300">{text.review}</span></div></article>)}</div><p className="site-muted mx-auto mt-6 max-w-3xl text-center text-sm">{text.contactReview}</p></div></section>

    <section id="academic" className="site-section"><div className="site-wrap"><SectionHeader eyebrow={text.educationEyebrow} title={text.educationTitle} text={text.educationText} /><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{publicSubjects.map(subject => <Card key={subject} icon={BookOpen} title={subject}>{text.portalEmpty}</Card>)}</div><div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-4">{[[CalendarDays, text.schedule], [Trophy, text.gpa], [Trophy, text.olympiads], [BookOpen, text.resources]].map(([Icon, title]) => <Card key={String(title)} icon={Icon as typeof BookOpen} title={title as string}>{text.portalEmpty}</Card>)}</div></div></section>
    <section id="videolessons" className="site-section site-tint"><div className="site-wrap"><SectionHeader eyebrow={text.educationEyebrow} title={text.videos} text={text.languageContent} /><EmptyState><PlayCircle className="mx-auto mb-2 h-7 w-7" />{text.videoEmpty}</EmptyState></div></section>

    <section id="school-life" className="site-section"><div className="site-wrap"><SectionHeader eyebrow={text.lifeEyebrow} title={text.lifeTitle} text={text.lifeText} /><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[[Building2, text.dormitory], [Users, text.meals], [Clock3, text.daily], [Trophy, text.sport], [Sparkles, text.clubs], [CalendarDays, text.events], [Users, text.studentLife], [ShieldCheck, text.president]].map(([Icon, title]) => <Card key={String(title)} icon={Icon as typeof Building2} title={title as string}>{text.lifeEmpty}</Card>)}</div></div></section>

    <section id="news" className="site-section site-tint"><div className="site-wrap"><SectionHeader eyebrow={text.newsEyebrow} title={text.newsTitle} text={text.newsText} />{announcements.length ? <div className="mt-10 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{announcements.slice(0, 6).map(item => <Card key={item.id ?? `${item.title}-${item.date}`} icon={Megaphone} title={item.title || text.newsTitle}><p>{item.date}</p><p className="mt-2">{item.content || item.description || item.message}</p></Card>)}</div> : <EmptyState>{text.newsEmpty}</EmptyState>}<div className="mt-14 grid gap-7 lg:grid-cols-2"><div><h3 className="site-subheading">{text.eventsTitle}</h3>{events === null ? <p className="site-muted mt-4">{text.loading}</p> : events.length ? <div className="mt-4 space-y-3">{events.map(item => <Card key={item.id ?? item.title} icon={CalendarDays} title={item.title || text.eventsTitle}><p>{item.date} {item.time && `· ${item.time}`}</p><p>{item.location}</p><p>{item.description}</p></Card>)}</div> : <EmptyState>{text.eventsEmpty}</EmptyState>}</div><div><h3 className="site-subheading">{text.achievementsTitle}</h3>{achievements === null ? <p className="site-muted mt-4">{text.loading}</p> : achievements.length ? <div className="mt-4 space-y-3">{achievements.map(item => <Card key={item.id ?? item.title} icon={Trophy} title={item.title || text.achievementsTitle}><p>{item.year} · {item.category}</p><p>{item.result || item.description}</p></Card>)}</div> : <EmptyState>{text.achievementsEmpty}</EmptyState>}</div></div></div></section>

    <section id="innovation" className="site-section"><div className="site-wrap"><SectionHeader eyebrow={text.moreEyebrow} title={text.moreTitle} text={text.innovationText} /><div className="mt-10 grid gap-4 md:grid-cols-3"><Card icon={Lightbulb} title={text.innovation}>{text.innovationText}</Card><Card icon={GalleryHorizontal} title={text.gallery}>{text.galleryEmpty}</Card><Card icon={Megaphone} title={text.media}>{text.mediaText}</Card></div></div></section>
    <section id="gallery" className="site-section site-tint"><div className="site-wrap"><SectionHeader eyebrow={text.moreEyebrow} title={text.gallery} text={text.mediaText} /><EmptyState>{text.galleryEmpty}</EmptyState></div></section>

    <section id="contact" className="site-section"><div className="site-wrap"><SectionHeader eyebrow={text.contactEyebrow} title={text.contactTitle} text={text.contactText} /><div className="mx-auto mt-10 max-w-2xl"><div className="site-card"><div className="flex gap-3"><MapPin className="h-6 w-6 shrink-0 text-[#0071e3]" /><p className="site-muted text-sm">{text.contactReview}</p></div><form className="mt-6 space-y-4" onSubmit={submit}><label className="block text-sm font-semibold"><span className="sr-only">{text.name}</span><input value={form.name} onChange={event => setForm(value => ({ ...value, name: event.target.value }))} placeholder={text.name} className="site-input" autoComplete="name" /></label><label className="block text-sm font-semibold"><span className="sr-only">{text.message}</span><textarea value={form.message} onChange={event => setForm(value => ({ ...value, message: event.target.value }))} placeholder={text.message} className="site-input min-h-32" required /></label><button type="submit" className="site-primary" disabled={formState === 'sending'}><Send className="h-4 w-4" />{formState === 'sending' ? text.sending : text.send}</button>{formState === 'sent' && <p className="flex items-center gap-2 text-sm text-emerald-700 dark:text-emerald-300"><CheckCircle2 className="h-4 w-4" />{text.sent}</p>}{formState === 'error' && <p role="alert" className="text-sm text-red-700 dark:text-red-300">{supabaseConfigured ? text.sendError : text.unavailable}</p>}</form></div></div></div></section>
    <footer className="border-t border-slate-200 bg-white/70 py-8 text-center text-sm text-slate-600 dark:border-slate-700 dark:bg-slate-950/50 dark:text-slate-300"><p>{text.footer}</p><p className="mt-2">© {new Date().getFullYear()} · {text.rights}</p></footer>
  </main>;
}
