import { useEffect, useMemo, useState } from 'react';
import { Coins, Gift, LogIn, LogOut, X, Check, ShieldCheck, ShoppingBag, Sparkles, Trophy, Zap } from 'lucide-react';
import { supabase, signInAdmin } from '../lib/supabase';

interface Props { onClose: () => void; }
type Student={id:string;student_code:string;full_name:string;class_name:string;balance:number};
type Reward={id:string;title:string;description:string;category:string;price:number;stock:number;image?:string};

const categoryMeta:Record<string,{emoji:string;label:string}>={
  Academic:{emoji:'📚',label:'Academic'}, Sport:{emoji:'🏃',label:'Sport'}, 'Culture & Creativity':{emoji:'🎨',label:'Culture & Creativity'},
  'Leadership & Volunteering':{emoji:'🤝',label:'Leadership & Volunteering'}, Technology:{emoji:'💻',label:'Technology'}, Environment:{emoji:'🌱',label:'Environment'},
  'Personal Development':{emoji:'📖',label:'Personal Development'}, Achievements:{emoji:'🏆',label:'Achievements'}
};

export default function SchoolCoin({onClose}:Props){
 const [mode,setMode]=useState<'student'|'admin'>('student');
 const [code,setCode]=useState(''),[pin,setPin]=useState(''),[student,setStudent]=useState<Student|null>(null);
 const [activities,setActivities]=useState<any[]>([]),[rewards,setRewards]=useState<Reward[]>([]),[orders,setOrders]=useState<any[]>([]),[requests,setRequests]=useState<any[]>([]);
 const [adminSession,setAdminSession]=useState<any>(null),[adminEmail,setAdminEmail]=useState(''),[adminPassword,setAdminPassword]=useState('');
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[coinBurst,setCoinBurst]=useState(0),[activeCategory,setActiveCategory]=useState('All');
 const flash=(s:string)=>{setNotice(s);setTimeout(()=>setNotice(''),2800)};
 const loadMarket=async()=>{const {data,error}=await supabase.from('schoolcoin_market_rewards').select('*').eq('active',true).order('category').order('price');if(error)setError(error.message);else setRewards(data||[])};
 const loadStudent=async(s:Student)=>{const {data}=await supabase.from('schoolcoin_orders').select('id,status,price,created_at,schoolcoin_market_rewards(title)').eq('student_id',s.id).order('created_at',{ascending:false});setOrders(data||[])};
 const login=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{const {data,error}=await supabase.rpc('schoolcoin_student_login',{p_code:code,p_pin:pin});if(error)throw error;const s=data as Student;setStudent(s);await Promise.all([loadMarket(),loadStudent(s)]);flash('Welcome to SchoolCoin ✨')}catch(e:any){setError(e.message||'Kirishda xatolik')}finally{setBusy(false)}};
 const loadCatalog=async()=>{const {data,error}=await supabase.from('schoolcoin_activities').select('*').eq('active',true).order('category').order('coin_reward',{ascending:false});if(error)setError(error.message);else setActivities(data||[])};
 useEffect(()=>{if(mode==='student'){loadCatalog();loadMarket()}},[mode]);
 const submit=async(id:string)=>{setBusy(true);setError('');try{const {error}=await supabase.rpc('schoolcoin_submit_request',{p_code:code,p_pin:pin,p_activity_id:id,p_evidence_url:null,p_note:null});if(error)throw error;setCoinBurst(x=>x+1);flash('⚡ Activity so‘rovi yuborildi! Admin tasdiqlagach coin keladi.')}catch(e:any){setError(e.message||'So‘rov yuborilmadi')}finally{setBusy(false)}};
 const redeem=async(r:Reward)=>{if(r.stock<1)return;setBusy(true);setError('');try{const {data,error}=await supabase.rpc('schoolcoin_market_redeem',{p_code:code,p_pin:pin,p_reward_id:r.id});if(error)throw error;const next=Number(data?.new_balance??(student?.balance||0)-r.price);setStudent(s=>s?{...s,balance:next}:s);if(student)await loadStudent({...student,balance:next});await loadMarket();setCoinBurst(x=>x+1);flash('🎁 Buyurtma yuborildi! Admin tayyorlaydi.')}catch(e:any){setError(e.message||'Redeem amalga oshmadi')}finally{setBusy(false)}};
 const adminLogin=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{const r=await signInAdmin(adminEmail.trim(),adminPassword);setAdminSession(r.session);await loadAdmin()}catch(e:any){setError(e.message||'Admin kirishda xatolik')}finally{setBusy(false)}};
 const loadAdmin=async()=>{const {data,error}=await supabase.from('schoolcoin_orders').select('id,status,price,created_at,student_id,schoolcoin_students(full_name,student_code),schoolcoin_market_rewards(title)').order('created_at',{ascending:false});if(error)setError(error.message);else setOrders(data||[]);const q=await supabase.from('schoolcoin_requests').select('id,status,created_at,student_id,activity_id,schoolcoin_students(full_name,student_code),schoolcoin_activities(name,coin_reward)').eq('status','pending').order('created_at',{ascending:false});if(!q.error)setRequests(q.data||[])};
 const approveActivity=async(id:string,yes:boolean)=>{setBusy(true);try{const {error}=await supabase.rpc('schoolcoin_admin_approve_request',{p_request_id:id,p_approve:yes});if(error)throw error;setCoinBurst(x=>x+1);flash(yes?'🪙 Coin berildi ✓':'So‘rov rad etildi');await loadAdmin()}catch(e:any){setError(e.message||'Amal bajarilmadi')}finally{setBusy(false)}};
 const updateOrder=async(id:string,status:string)=>{setBusy(true);const {error}=await supabase.from('schoolcoin_orders').update({status,updated_at:new Date().toISOString()}).eq('id',id);if(error)setError(error.message);else{flash('📦 Buyurtma yangilandi ✓');await loadAdmin()}setBusy(false)};
 const categories=useMemo(()=>['All',...Object.keys(categoryMeta).filter(c=>activities.some(a=>a.category===c))],[activities]);
 const filtered=activeCategory==='All'?activities:activities.filter(a=>a.category===activeCategory);
 return <div className="fixed inset-0 z-[120] overflow-auto bg-slate-950/70 backdrop-blur-xl p-3 md:p-6"><style>{`@keyframes scFloat{0%{opacity:0;transform:translateY(12px) scale(.7)}25%{opacity:1}100%{opacity:0;transform:translateY(-90px) scale(1.25)}}@keyframes scPop{0%{transform:scale(.85);opacity:0}60%{transform:scale(1.04);opacity:1}100%{transform:scale(1);opacity:1}}@keyframes scShine{0%{transform:translateX(-130%)}100%{transform:translateX(180%)}}.sc-pop{animation:scPop .35s ease-out}.sc-float{animation:scFloat 1.25s ease-out forwards}.sc-card{transition:transform .25s ease,box-shadow .25s ease}.sc-card:hover{transform:translateY(-5px);box-shadow:0 18px 40px rgba(15,23,42,.10)}.sc-shine{position:relative;overflow:hidden}.sc-shine:after{content:'';position:absolute;inset:0;width:35%;background:linear-gradient(90deg,transparent,rgba(255,255,255,.5),transparent);transform:translateX(-130%);animation:scShine 2.8s infinite}`}</style>
 <div className="mx-auto min-h-[calc(100vh-24px)] max-w-6xl rounded-[32px] bg-slate-50 shadow-2xl overflow-hidden">
 <header className="sticky top-0 z-10 flex items-center justify-between border-b bg-white/95 px-5 py-4 backdrop-blur"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-amber-100 text-amber-600 animate-pulse"><Coins/></div><div><h1 className="font-black text-xl">SchoolCoin</h1><p className="text-xs text-slate-500">Student economy & reward system</p></div></div><div className="flex gap-2"><button onClick={()=>setMode('student')} className={`rounded-xl px-3 py-2 text-sm font-semibold transition ${mode==='student'?'bg-slate-900 text-white':'bg-slate-100 hover:bg-slate-200'}`}>Student</button><button onClick={()=>setMode('admin')} className={`rounded-xl px-3 py-2 text-sm font-semibold transition ${mode==='admin'?'bg-slate-900 text-white':'bg-slate-100 hover:bg-slate-200'}`}>Admin</button><button onClick={onClose} className="p-2 transition hover:rotate-90"><X/></button></div></header>
 <main className="p-5 md:p-7">{error&&<div className="mb-4 rounded-2xl bg-red-50 p-3 text-sm text-red-700 sc-pop">{error}</div>}{notice&&<div className="mb-4 rounded-2xl bg-emerald-50 p-3 text-sm text-emerald-700 sc-pop">{notice}</div>}
 {coinBurst>0&&<div key={coinBurst} className="pointer-events-none fixed right-8 top-24 z-[200] text-3xl font-black text-amber-500 sc-float">+🪙</div>}
 {mode==='student'&&!student&&<section className="mx-auto max-w-md rounded-3xl bg-white p-7 shadow-sm sc-pop"><div className="mb-6 text-center"><Coins className="mx-auto h-10 w-10 text-amber-500 animate-bounce"/><h2 className="mt-3 text-2xl font-black">Student Login</h2><p className="mt-1 text-sm text-slate-500">Kod va PIN orqali SchoolCoin hisobingizga kiring.</p></div><form onSubmit={login} className="space-y-3"><input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="Student code (STU001)" className="w-full rounded-2xl border p-3.5 outline-none transition focus:ring-4 focus:ring-amber-100" required/><input value={pin} onChange={e=>setPin(e.target.value)} type="password" placeholder="PIN" className="w-full rounded-2xl border p-3.5 outline-none transition focus:ring-4 focus:ring-amber-100" required/><button disabled={busy} className="sc-shine w-full rounded-2xl bg-slate-900 py-3.5 font-bold text-white transition hover:-translate-y-0.5 disabled:opacity-50"><LogIn className="mr-1 inline h-4 w-4"/>{busy?'Kirilmoqda…':'Kirish'}</button></form></section>}
 {mode==='student'&&student&&<div className="space-y-7 sc-pop"><section className="grid gap-4 md:grid-cols-3"><div className="md:col-span-2 rounded-3xl bg-slate-900 p-6 text-white sc-shine"><p className="text-sm text-white/60">Salom, {student.full_name} 👋</p><h2 className="mt-1 text-3xl font-black transition-all">{student.balance} SchoolCoin</h2><p className="mt-2 text-sm text-white/60">{student.class_name} · {student.student_code}</p><div className="mt-5 flex gap-2 text-xs"><span className="rounded-full bg-white/10 px-3 py-1">⚡ Earn</span><span className="rounded-full bg-white/10 px-3 py-1">🏪 Market</span><span className="rounded-full bg-white/10 px-3 py-1">🏆 Achievements</span></div></div><button onClick={()=>{setStudent(null);setCode('');setPin('');}} className="rounded-3xl bg-white p-5 text-left shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><LogOut/><p className="mt-3 font-bold">Chiqish</p></button></section>
 <section><div className="mb-4 flex items-center justify-between"><h3 className="text-xl font-black">🪙 Coin olish</h3><span className="rounded-full bg-amber-100 px-3 py-1 text-xs font-black text-amber-700">{activities.length} activities</span></div><div className="mb-4 flex gap-2 overflow-x-auto pb-1">{categories.map(c=><button key={c} onClick={()=>setActiveCategory(c)} className={`shrink-0 rounded-full px-3 py-2 text-xs font-bold transition ${activeCategory===c?'bg-slate-900 text-white scale-105':'bg-white hover:bg-slate-100'}`}>{c==='All'?'✨ All':`${categoryMeta[c]?.emoji||'🪙'} ${categoryMeta[c]?.label||c}`}</button>)}</div><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3">{filtered.map(a=><article key={a.id} className="sc-card rounded-3xl bg-white p-5 shadow-sm"><div className="flex justify-between gap-3"><div><b>{a.name}</b><p className="mt-1 text-xs text-slate-500">{categoryMeta[a.category]?.emoji||'🪙'} {a.category}</p></div><span className="sc-shine rounded-full bg-amber-100 px-3 py-1 text-sm font-black text-amber-700">+{a.coin_reward}</span></div><button disabled={busy} onClick={()=>submit(a.id)} className="mt-4 w-full rounded-xl bg-amber-500 py-2.5 text-sm font-bold text-white transition hover:-translate-y-0.5 hover:bg-amber-600 disabled:opacity-40"><Zap className="mr-1 inline h-4 w-4"/>So‘rov yuborish</button></article>)}</div></section>
 <section><div className="mb-3 flex items-center justify-between"><h3 className="text-xl font-black">🏪 SchoolCoin Market</h3><span className="text-xs text-slate-500">Haqiqiy sovg‘alar</span></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{rewards.map(r=><article key={r.id} className="sc-card overflow-hidden rounded-3xl bg-white shadow-sm">{r.image?<img src={r.image} className="h-40 w-full object-cover transition duration-500 hover:scale-105"/>:<div className="grid h-28 place-items-center bg-gradient-to-br from-amber-50 to-violet-50"><Gift className="h-12 w-12 text-amber-500 animate-pulse"/></div>}<div className="p-5"><div className="flex justify-between"><span className="rounded-full bg-violet-100 px-2.5 py-1 text-xs font-bold text-violet-700">{r.category}</span><span className="text-xs text-slate-500">Stock: {r.stock}</span></div><h4 className="mt-3 text-lg font-black">{r.title}</h4><p className="mt-1 min-h-10 text-sm text-slate-500">{r.description}</p><div className="mt-4 flex items-center justify-between"><b className="text-lg">{r.price} 🪙</b><button disabled={busy||r.stock<1} onClick={()=>redeem(r)} className="rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-bold text-white transition hover:scale-105 disabled:opacity-40">{r.stock<1?'Tugagan':'Sotib olish'}</button></div></div></article>)}</div></section>
 <section><div className="mb-3 flex items-center gap-2"><ShoppingBag/><h3 className="text-xl font-black">📦 Mening buyurtmalarim</h3></div><div className="space-y-2">{orders.length?orders.map(o=><div key={o.id} className="sc-card flex items-center justify-between rounded-2xl bg-white p-4 shadow-sm"><div><b>{o.schoolcoin_market_rewards?.title||'Reward'}</b><p className="text-xs text-slate-500">{o.price} coin · {new Date(o.created_at).toLocaleString()}</p></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold capitalize">{o.status}</span></div>):<div className="rounded-2xl bg-white p-5 text-sm text-slate-500">Hali buyurtma yo‘q.</div>}</div></section></div>}
 {mode==='admin'&&!adminSession&&<section className="mx-auto max-w-md rounded-3xl bg-white p-7 shadow-sm sc-pop"><ShieldCheck className="mx-auto h-10 w-10 text-blue-600 animate-pulse"/><h2 className="mt-3 text-center text-2xl font-black">SchoolCoin Admin</h2><form onSubmit={adminLogin} className="mt-6 space-y-3"><input type="email" value={adminEmail} onChange={e=>setAdminEmail(e.target.value)} placeholder="Admin email" className="w-full rounded-2xl border p-3.5" required/><input type="password" value={adminPassword} onChange={e=>setAdminPassword(e.target.value)} placeholder="Parol" className="w-full rounded-2xl border p-3.5" required/><button className="w-full rounded-2xl bg-blue-600 py-3.5 font-bold text-white transition hover:-translate-y-0.5">Kirish</button></form></section>}
 {mode==='admin'&&adminSession&&<div className="space-y-6 sc-pop"><section className="rounded-3xl bg-white p-6 shadow-sm"><h3 className="mb-4 text-xl font-black">🪙 Activity approvals</h3>{requests.length?requests.map(q=><div key={q.id} className="flex flex-col gap-3 border-b py-4 last:border-0 md:flex-row md:items-center md:justify-between"><div><b>{q.schoolcoin_students?.full_name} · {q.schoolcoin_activities?.name}</b><p className="text-xs text-slate-500">+{q.schoolcoin_activities?.coin_reward} coin</p></div><div className="flex gap-2"><button onClick={()=>approveActivity(q.id,true)} className="rounded-xl bg-emerald-600 px-3 py-2 text-sm font-bold text-white transition hover:scale-105"><Check className="mr-1 inline h-4 w-4"/>Approve</button><button onClick={()=>approveActivity(q.id,false)} className="rounded-xl bg-red-50 px-3 py-2 text-sm font-bold text-red-700 transition hover:scale-105">Reject</button></div></div>):<p className="text-sm text-slate-500">Pending activity yo‘q.</p>}</section><section className="rounded-3xl bg-white p-6 shadow-sm"><h3 className="mb-4 text-xl font-black">🏪 Market orders</h3>{orders.length?orders.map(o=><div key={o.id} className="flex flex-col gap-3 border-b py-4 last:border-0 md:flex-row md:items-center md:justify-between"><div><b>{o.schoolcoin_students?.full_name} → {o.schoolcoin_market_rewards?.title}</b><p className="text-xs text-slate-500">{o.price} coin · {o.status}</p></div><div className="flex gap-2">{o.status==='pending'&&<button onClick={()=>updateOrder(o.id,'approved')} className="rounded-xl bg-blue-600 px-3 py-2 text-sm font-bold text-white transition hover:scale-105">Approve</button>}{o.status==='approved'&&<button onClick={()=>updateOrder(o.id,'ready')} className="rounded-xl bg-amber-500 px-3 py-2 text-sm font-bold text-white transition hover:scale-105">Ready</button>}{o.status==='ready'&&<button onClick={()=>updateOrder(o.id,'delivered')} className="rounded-xl bg-emerald-600 px-3 py-2 text-sm font-bold text-white transition hover:scale-105">Delivered</button>}</div></div>):<p className="text-sm text-slate-500">Buyurtma yo‘q.</p>}</section></div>}
 </main></div></div>;
}
