import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import { Activity, CheckCircle2, Coins, Gift, History, LayoutDashboard, LogOut, Search, ShoppingBag, Upload, Users, X, XCircle } from 'lucide-react';
import { bindStudent, ensureStudentAuthSession, getCurrentStudent, signInAdmin, signOutLocal, supabase } from '../lib/supabase';

interface Props { onClose: () => void; initialMode?: 'student' | 'admin'; adminSession?: { user?: { email?: string; app_metadata?: { role?: string } } } | null; }
type Student = { id: string; student_code: string; full_name: string; class_name: string; balance: number };
type ActivityItem = { id: string; name: string; category: string; coin_reward: number; description?: string; max_per_month?: number | null; requires_evidence?: boolean };
type Reward = { id: string; title: string; description: string; category: string; price: number; stock: number };
type Order = { id: string; status: string; price: number; created_at: string; reward_title: string };
type RequestItem = { activity_name: string; status: string; created_at: string; evidence_url?: string | null };
type Transaction = { amount: number; transaction_type: string; note?: string | null; created_at: string };
type Progress = { activity_id: string; approved_count: number; pending_count: number; max_per_month: number | null };
type AdminStudent = { id: string; student_code: string; full_name: string; class_name: string; active: boolean; balance: number };
type AdminRequest = { id: string; status: string; created_at: string; evidence_url?: string | null; student?: { full_name?: string; student_code?: string } | null; activity?: { name?: string; coin_reward?: number } | null };
type AdminTransaction = { id: string; student_id: string; amount: number; transaction_type: string; note?: string | null; created_at: string };
type Tab = 'dashboard' | 'students' | 'activities' | 'approvals' | 'market' | 'orders' | 'transactions';
const date = (v: string) => new Date(v).toLocaleString('uz-UZ', { dateStyle: 'medium', timeStyle: 'short' });

export default function SchoolCoinSecure({ onClose, initialMode = 'student', adminSession = null }: Props) {
  const [mode, setMode] = useState<'student' | 'admin'>(initialMode), [student, setStudent] = useState<Student | null>(null);
  const [code, setCode] = useState(''), [pin, setPin] = useState(''), [activities, setActivities] = useState<ActivityItem[]>([]), [rewards, setRewards] = useState<Reward[]>([]);
  const [orders, setOrders] = useState<Order[]>([]), [requests, setRequests] = useState<RequestItem[]>([]), [transactions, setTransactions] = useState<Transaction[]>([]), [progress, setProgress] = useState<Progress[]>([]);
  const [adminState, setAdminState] = useState(adminSession), [students, setStudents] = useState<AdminStudent[]>([]), [adminRequests, setAdminRequests] = useState<AdminRequest[]>([]), [adminTransactions, setAdminTransactions] = useState<AdminTransaction[]>([]);
  const [adminEmail, setAdminEmail] = useState(''), [adminPassword, setAdminPassword] = useState(''), [tab, setTab] = useState<Tab>('dashboard'), [search, setSearch] = useState(''), [category, setCategory] = useState('All');
  const [busy, setBusy] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState('');
  const [selectedActivity, setSelectedActivity] = useState<ActivityItem | null>(null), [evidencePath, setEvidencePath] = useState(''), [evidenceName, setEvidenceName] = useState(''), [note, setNote] = useState('');
  const admin = adminState?.user?.app_metadata?.role === 'admin';
  const fail = useCallback((e: unknown, fallback: string) => setError(e instanceof Error ? e.message : fallback), []);
  const flash = useCallback((v: string) => { setNotice(v); window.setTimeout(() => setNotice(''), 2400); }, []);

  const loadCatalog = useCallback(async () => {
    const [a, r] = await Promise.all([
      supabase.from('schoolcoin_activities').select('*').eq('active', true).order('category').order('coin_reward', { ascending: false }),
      supabase.from('schoolcoin_market_rewards').select('*').eq('active', true).order('category').order('price'),
    ]);
    if (a.error) throw a.error; if (r.error) throw r.error;
    setActivities((a.data || []) as ActivityItem[]); setRewards((r.data || []) as Reward[]);
  }, []);

  const loadStudent = useCallback(async () => {
    const current = await getCurrentStudent();
    if (!current) { setStudent(null); return; }
    setStudent(current);
    const [o, t, q, p] = await Promise.all([supabase.rpc('schoolcoin_student_orders'), supabase.rpc('schoolcoin_student_transactions'), supabase.rpc('schoolcoin_student_requests'), supabase.rpc('schoolcoin_student_activity_progress')]);
    for (const r of [o, t, q, p]) if (r.error) throw r.error;
    setOrders((o.data || []) as Order[]); setTransactions((t.data || []) as Transaction[]); setRequests((q.data || []) as RequestItem[]); setProgress((p.data || []) as Progress[]);
  }, []);

  const loadAdmin = useCallback(async () => {
    setBusy(true); setError('');
    try {
      const [s, q, t, o, a, r] = await Promise.all([
        supabase.rpc('schoolcoin_admin_student_balances'),
        supabase.from('schoolcoin_requests').select('id,status,created_at,evidence_url,schoolcoin_students(full_name,student_code),schoolcoin_activities(name,coin_reward)').eq('status', 'pending').order('created_at', { ascending: false }),
        supabase.from('schoolcoin_transactions').select('id,student_id,amount,transaction_type,note,created_at').order('created_at', { ascending: false }).limit(200),
        supabase.from('schoolcoin_orders').select('id,status,price,created_at,schoolcoin_market_rewards(title)').order('created_at', { ascending: false }),
        supabase.from('schoolcoin_activities').select('*').eq('active', true).order('category').order('coin_reward', { ascending: false }),
        supabase.from('schoolcoin_market_rewards').select('*').eq('active', true).order('category').order('price'),
      ]);
      for (const r of [s, q, t, o, a, r]) if (r.error) throw r.error;
      setStudents((s.data || []) as AdminStudent[]); setAdminTransactions((t.data || []) as AdminTransaction[]); setActivities((a.data || []) as ActivityItem[]); setRewards((r.data || []) as Reward[]);
      setAdminRequests(((q.data || []) as Array<Record<string, unknown>>).map(x => ({ id: String(x.id), status: String(x.status), created_at: String(x.created_at), evidence_url: x.evidence_url as string | null, student: x.schoolcoin_students as AdminRequest['student'], activity: x.schoolcoin_activities as AdminRequest['activity'] })));
      setOrders(((o.data || []) as Array<Record<string, unknown>>).map(x => ({ id: String(x.id), status: String(x.status), price: Number(x.price), created_at: String(x.created_at), reward_title: String((x.schoolcoin_market_rewards as { title?: string } | null)?.title || 'Reward') })));
    } catch (e) { fail(e, 'Admin ma’lumotlari yuklanmadi'); } finally { setBusy(false); }
  }, [fail]);

  useEffect(() => setAdminState(adminSession), [adminSession]);
  useEffect(() => { void loadCatalog().catch(e => fail(e, 'SchoolCoin katalogi yuklanmadi')); }, [loadCatalog, fail]);
  useEffect(() => { if (mode !== 'student' || student) return; void supabase.auth.getSession().then(({ data }) => { if (data.session?.user?.is_anonymous) void loadStudent().catch(e => console.error(e)); }); }, [mode, student, loadStudent]);
  useEffect(() => { if (mode === 'admin' && admin) void loadAdmin(); }, [mode, admin, loadAdmin]);

  const studentLogin = async (e: FormEvent) => {
    e.preventDefault(); setBusy(true); setError('');
    try { await ensureStudentAuthSession(); await bindStudent(code, pin); await loadStudent(); setCode(''); setPin(''); flash('SchoolCoin hisobingiz ochildi ✨'); }
    catch (err) { await signOutLocal().catch(() => undefined); fail(err, 'Student kirishda xatolik'); }
    finally { setBusy(false); }
  };

  const uploadEvidence = async (file: File) => {
    if (file.size > 5 * 1024 * 1024) throw new Error('Evidence 5 MB dan kichik bo‘lishi kerak.');
    if (!['image/jpeg','image/png','image/webp','application/pdf'].includes(file.type)) throw new Error('Faqat JPG, PNG, WebP yoki PDF yuklash mumkin.');
    const { data } = await supabase.auth.getUser(); if (!data.user?.is_anonymous) throw new Error('Student sessiyasi kerak.');
    const ext = file.name.split('.').pop()?.toLowerCase() || 'bin', path = `${data.user.id}/${crypto.randomUUID()}.${ext}`;
    const { error: uploadError } = await supabase.storage.from('schoolcoin-evidence').upload(path, file, { contentType: file.type, upsert: false });
    if (uploadError) throw uploadError; setEvidencePath(path); setEvidenceName(file.name);
  };

  const submitActivity = async () => {
    if (!selectedActivity) return; setBusy(true); setError('');
    try {
      if (selectedActivity.requires_evidence && !evidencePath) throw new Error('Bu faoliyat uchun evidence majburiy.');
      const { error: rpcError } = await supabase.rpc('schoolcoin_submit_request', { p_activity_id: selectedActivity.id, p_evidence_url: evidencePath || null, p_note: note.trim() || null });
      if (rpcError) throw rpcError; setSelectedActivity(null); setEvidencePath(''); setEvidenceName(''); setNote(''); await loadStudent(); flash('So‘rov yuborildi ✓');
    } catch (err) { fail(err, 'So‘rov yuborilmadi'); } finally { setBusy(false); }
  };

  const redeem = async (reward: Reward) => {
    if (!student || reward.stock < 1 || student.balance < reward.price) return; setBusy(true); setError('');
    try { const { data, error: rpcError } = await supabase.rpc('schoolcoin_market_redeem', { p_reward_id: reward.id }); if (rpcError) throw rpcError; const b = Number((data as { new_balance?: number } | null)?.new_balance); if (Number.isFinite(b)) setStudent(s => s ? { ...s, balance: b } : s); await Promise.all([loadCatalog(), loadStudent()]); flash('Buyurtma yuborildi 🎁'); }
    catch (err) { fail(err, 'Redeem amalga oshmadi'); } finally { setBusy(false); }
  };

  const adminLogin = async (e: FormEvent) => { e.preventDefault(); setBusy(true); setError(''); try { const r = await signInAdmin(adminEmail.trim(), adminPassword); setAdminState(r.session as typeof adminState); setMode('admin'); setAdminPassword(''); } catch (err) { fail(err, 'Admin kirishda xatolik'); } finally { setBusy(false); } };
  const approve = async (id: string, allow: boolean) => { setBusy(true); try { const { error: r } = await supabase.rpc('schoolcoin_admin_approve_request', { p_request_id: id, p_approve: allow }); if (r) throw r; await loadAdmin(); flash(allow ? 'Coin berildi ✓' : 'So‘rov rad etildi'); } catch (err) { fail(err, 'Amal bajarilmadi'); } finally { setBusy(false); } };
  const updateOrder = async (id: string, status: string) => { setBusy(true); try { const { error: r } = await supabase.rpc('schoolcoin_admin_update_order_status', { p_order_id: id, p_status: status }); if (r) throw r; await loadAdmin(); flash('Buyurtma yangilandi ✓'); } catch (err) { fail(err, 'Buyurtma yangilanmadi'); } finally { setBusy(false); } };
  const openEvidence = async (path: string) => { try { const { data, error: r } = await supabase.storage.from('schoolcoin-evidence').createSignedUrl(path, 300); if (r) throw r; window.open(data.signedUrl, '_blank', 'noopener,noreferrer'); } catch (err) { fail(err, 'Evidence ochilmadi'); } };
  const logout = async () => { try { await signOutLocal(); setStudent(null); setAdminState(null); setOrders([]); setRequests([]); setTransactions([]); setProgress([]); setMode('student'); } catch (err) { fail(err, 'Sessiyadan chiqib bo‘lmadi'); } };

  const categories = ['All', ...Array.from(new Set(activities.map(x => x.category).filter(Boolean)))], filtered = category === 'All' ? activities : activities.filter(x => x.category === category);
  const progressMap = useMemo(() => new Map(progress.map(x => [x.activity_id, x])), [progress]);
  const filteredStudents = useMemo(() => { const q = search.trim().toLowerCase(); return q ? students.filter(x => `${x.full_name} ${x.student_code} ${x.class_name}`.toLowerCase().includes(q)) : students; }, [students, search]);
  const totalCoins = students.reduce((sum, x) => sum + x.balance, 0);

  return <div className="fixed inset-0 z-[120] overflow-auto bg-slate-950/70 p-3 backdrop-blur-xl md:p-6"><div className="mx-auto min-h-[calc(100vh-24px)] max-w-7xl overflow-hidden rounded-[28px] bg-slate-50 shadow-2xl">
    <header className="sticky top-0 z-20 flex flex-wrap items-center justify-between gap-3 border-b bg-white/95 px-4 py-4 backdrop-blur"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-amber-100 text-amber-600"><Coins /></div><div><h1 className="text-lg font-black">SchoolCoin</h1><p className="text-xs text-slate-500">Student economy & rewards</p></div></div><div className="flex gap-2"><button type="button" onClick={() => setMode('student')} className={`rounded-xl px-3 py-2 text-sm font-semibold ${mode === 'student' ? 'bg-slate-900 text-white' : 'bg-slate-100'}`}>Student</button><button type="button" onClick={() => setMode('admin')} className={`rounded-xl px-3 py-2 text-sm font-semibold ${mode === 'admin' ? 'bg-slate-900 text-white' : 'bg-slate-100'}`}>Admin</button><button type="button" onClick={onClose} className="rounded-xl p-2" aria-label="Yopish"><X /></button></div></header>
    <main className="p-4 md:p-6">{error && <div role="alert" className="mb-4 flex items-center justify-between gap-3 rounded-2xl bg-red-50 p-3 text-sm text-red-700"><span>{error}</span><button type="button" onClick={() => setError('')} aria-label="Xatoni yopish"><X className="h-4 w-4" /></button></div>}{notice && <div role="status" className="mb-4 rounded-2xl bg-emerald-50 p-3 text-sm font-semibold text-emerald-700">{notice}</div>}
      {mode === 'student' && !student && <section className="mx-auto max-w-md rounded-3xl bg-white p-7 shadow-sm"><div className="mb-6 text-center"><Coins className="mx-auto h-10 w-10 text-amber-500" /><h2 className="mt-3 text-2xl font-black">Student Login</h2><p className="mt-2 text-sm text-slate-500">Kod va PIN bir marta tekshiriladi; keyingi amallar auth sessiyasi bilan himoyalanadi.</p></div><form onSubmit={studentLogin} className="space-y-3"><label className="block text-sm font-semibold">Student code<input required value={code} onChange={e => setCode(e.target.value.toUpperCase())} placeholder="STU001" className="mt-1.5 w-full rounded-2xl border p-3.5" /></label><label className="block text-sm font-semibold">PIN<input required value={pin} onChange={e => setPin(e.target.value)} type="password" inputMode="numeric" autoComplete="current-password" placeholder="PIN" className="mt-1.5 w-full rounded-2xl border p-3.5" /></label><button disabled={busy} className="w-full rounded-2xl bg-slate-900 p-3.5 font-semibold text-white disabled:opacity-50">{busy ? 'Tekshirilmoqda…' : 'Kirish'}</button></form></section>}
      {mode === 'student' && student && <section className="space-y-6"><div className="grid gap-4 md:grid-cols-[1fr_auto]"><div className="rounded-3xl bg-slate-900 p-6 text-white"><p className="text-sm text-white/60">Student</p><h2 className="mt-1 text-2xl font-black">{student.full_name}</h2><p className="mt-1 text-sm text-white/60">{student.class_name} · {student.student_code}</p></div><div className="rounded-3xl bg-amber-50 p-6 text-right"><p className="text-xs font-bold uppercase text-amber-700">Balance</p><p className="mt-1 text-4xl font-black text-amber-700">{student.balance} 🪙</p><button type="button" onClick={() => void loadStudent()} className="mt-2 text-xs font-semibold text-amber-800">Yangilash</button></div></div>
        <section className="rounded-3xl bg-white p-5 shadow-sm"><div className="flex gap-2 overflow-x-auto">{categories.map(x => <button type="button" key={x} onClick={() => setCategory(x)} className={`shrink-0 rounded-full px-3 py-2 text-xs font-semibold ${category === x ? 'bg-slate-900 text-white' : 'bg-slate-100'}`}>{x}</button>)}</div><div className="mt-5 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{filtered.map(x => { const p = progressMap.get(x.id), left = x.max_per_month == null ? null : Math.max(0, x.max_per_month - (p?.approved_count || 0)); return <article key={x.id} className="rounded-2xl border p-4"><div className="flex items-start justify-between gap-3"><h3 className="font-bold">{x.name}</h3><span className="rounded-full bg-amber-50 px-2.5 py-1 text-xs font-bold text-amber-700">+{x.coin_reward}</span></div><p className="mt-2 text-sm text-slate-500">{x.description || 'Faoliyat uchun SchoolCoin oling.'}</p>{x.max_per_month != null && <p className="mt-3 text-xs font-semibold text-slate-500">Bu oy: {p?.approved_count || 0}/{x.max_per_month} · {left} qoldi</p>}{x.requires_evidence && <p className="mt-2 text-xs font-semibold text-blue-700">📎 Evidence required</p>}<button disabled={busy || left === 0} type="button" onClick={() => { setSelectedActivity(x); setEvidencePath(''); setEvidenceName(''); setNote(''); }} className="mt-4 w-full rounded-xl bg-slate-900 py-2.5 text-sm font-semibold text-white disabled:opacity-40">{left === 0 ? 'Oylik limit tugagan' : 'So‘rov yuborish'}</button></article>; })}</div></section>
        <section className="rounded-3xl bg-white p-5 shadow-sm"><div className="mb-4 flex items-center gap-2"><Gift className="h-5 w-5 text-amber-600" /><h3 className="font-bold">Market</h3></div><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{rewards.map(x => <article key={x.id} className="rounded-2xl border p-4"><div className="flex items-center justify-between gap-3"><h4 className="font-bold">{x.title}</h4><span className="font-bold text-amber-600">{x.price}</span></div><p className="mt-2 text-sm text-slate-500">{x.description}</p><p className="mt-2 text-xs text-slate-500">Stock: {x.stock}</p><button disabled={busy || x.stock < 1 || student.balance < x.price} type="button" onClick={() => void redeem(x)} className="mt-4 w-full rounded-xl bg-slate-900 py-2.5 text-sm font-semibold text-white disabled:opacity-40">{x.stock < 1 ? 'Tugagan' : student.balance < x.price ? 'Coin yetarli emas' : 'Sotib olish'}</button></article>)}</div></section>
        <div className="grid gap-6 lg:grid-cols-2"><section className="rounded-3xl bg-white p-5 shadow-sm"><h3 className="mb-4 flex items-center gap-2 font-bold"><History className="h-5 w-5" />Transaction history</h3>{transactions.length ? <div className="space-y-2">{transactions.map((x,i) => <div key={`${x.created_at}-${i}`} className="flex items-center justify-between rounded-2xl bg-slate-50 p-3"><div><b className="text-sm">{x.note || x.transaction_type}</b><p className="text-xs text-slate-500">{date(x.created_at)}</p></div><span className={`font-black ${x.amount >= 0 ? 'text-emerald-600' : 'text-red-600'}`}>{x.amount > 0 ? '+' : ''}{x.amount}</span></div>)}</div> : <p className="text-sm text-slate-500">Hozircha tranzaksiya yo‘q.</p>}</section><section className="rounded-3xl bg-white p-5 shadow-sm"><h3 className="mb-4 font-bold">Activity requests</h3>{requests.length ? <div className="space-y-2">{requests.map((x,i) => <div key={`${x.created_at}-${i}`} className="rounded-2xl bg-slate-50 p-3"><div className="flex items-center justify-between gap-3"><b className="text-sm">{x.activity_name}</b><span className={`rounded-full px-2 py-1 text-[11px] font-bold ${x.status === 'approved' ? 'bg-emerald-100 text-emerald-700' : x.status === 'rejected' ? 'bg-red-100 text-red-700' : 'bg-amber-100 text-amber-700'}`}>{x.status}</span></div><p className="mt-1 text-xs text-slate-500">{date(x.created_at)} {x.evidence_url ? '· 📎 evidence' : ''}</p></div>)}</div> : <p className="text-sm text-slate-500">Hozircha so‘rov yo‘q.</p>}</section></div>
        <section className="rounded-3xl bg-white p-5 shadow-sm"><h3 className="mb-4 flex items-center gap-2 font-bold"><ShoppingBag className="h-5 w-5" />Buyurtmalar</h3>{orders.length ? <div className="space-y-2">{orders.map(x => <div key={x.id} className="flex items-center justify-between rounded-2xl bg-slate-50 p-3"><div><b>{x.reward_title}</b><p className="text-xs text-slate-500">{date(x.created_at)}</p></div><div className="text-right"><b>{x.price} 🪙</b><p className="text-xs text-slate-500">{x.status}</p></div></div>)}</div> : <p className="text-sm text-slate-500">Hozircha buyurtma yo‘q.</p>}</section><button type="button" onClick={() => void logout()} className="inline-flex items-center gap-2 rounded-xl border px-4 py-2 text-sm font-semibold"><LogOut className="h-4 w-4" />Studentdan chiqish</button></section>}
      {mode === 'admin' && !admin && <section className="mx-auto max-w-md rounded-3xl bg-white p-7 shadow-sm"><div className="mb-6 text-center"><LayoutDashboard className="mx-auto h-10 w-10" /><h2 className="mt-3 text-2xl font-black">SchoolCoin Admin</h2></div><form onSubmit={adminLogin} className="space-y-3"><label className="block text-sm font-semibold">Admin email<input required type="email" value={adminEmail} onChange={e => setAdminEmail(e.target.value)} className="mt-1.5 w-full rounded-2xl border p-3.5" /></label><label className="block text-sm font-semibold">Parol<input required type="password" value={adminPassword} onChange={e => setAdminPassword(e.target.value)} className="mt-1.5 w-full rounded-2xl border p-3.5" /></label><button disabled={busy} className="w-full rounded-2xl bg-slate-900 p-3.5 font-semibold text-white">{busy ? 'Tekshirilmoqda…' : 'Kirish'}</button></form></section>}
      {mode === 'admin' && admin && <div className="grid gap-6 lg:grid-cols-[220px_1fr]"><aside className="rounded-3xl bg-slate-900 p-4 text-white">{([['dashboard',LayoutDashboard,'Dashboard'],['students',Users,'Students'],['activities',Activity,'Activities'],['approvals',CheckCircle2,'Approvals'],['market',Gift,'Market'],['orders',ShoppingBag,'Orders'],['transactions',History,'Transactions']] as const).map(([id,I,label]) => <button type="button" key={id} onClick={() => setTab(id)} className={`mb-1 flex w-full items-center gap-3 rounded-2xl px-3 py-3 text-left text-sm font-semibold ${tab === id ? 'bg-white text-slate-900' : 'text-white/75 hover:bg-white/10'}`}><I className="h-4 w-4" />{label}</button>)}<button type="button" onClick={() => void logout()} className="mt-4 flex w-full items-center gap-3 rounded-2xl px-3 py-3 text-sm font-semibold text-red-300"><LogOut className="h-4 w-4" />Chiqish</button></aside><section className="space-y-5">
        {tab === 'dashboard' && <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-3xl bg-white p-5"><p className="text-xs text-slate-500">Students</p><p className="mt-2 text-3xl font-black">{students.length}</p></div><div className="rounded-3xl bg-white p-5"><p className="text-xs text-slate-500">SchoolCoin</p><p className="mt-2 text-3xl font-black">{totalCoins}</p></div><div className="rounded-3xl bg-white p-5"><p className="text-xs text-slate-500">Approvals</p><p className="mt-2 text-3xl font-black">{adminRequests.length}</p></div><div className="rounded-3xl bg-white p-5"><p className="text-xs text-slate-500">Orders</p><p className="mt-2 text-3xl font-black">{orders.filter(x => x.status === 'pending').length}</p></div></div>}
        {tab === 'students' && <div className="rounded-3xl bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><h3 className="font-bold">Students</h3><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400" /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Qidirish" className="rounded-xl border py-2.5 pl-9 pr-3 text-sm" /></div></div><div className="mt-4 overflow-x-auto"><table className="min-w-full text-sm"><thead><tr className="border-b text-left text-slate-500"><th className="px-3 py-2">Student</th><th className="px-3 py-2">Class</th><th className="px-3 py-2">Code</th><th className="px-3 py-2">Balance</th></tr></thead><tbody>{filteredStudents.map(x => <tr key={x.id} className="border-b"><td className="px-3 py-3 font-semibold">{x.full_name}</td><td className="px-3 py-3">{x.class_name}</td><td className="px-3 py-3">{x.student_code}</td><td className="px-3 py-3 font-bold">{x.balance} 🪙</td></tr>)}</tbody></table></div></div>}
        {tab === 'activities' && <div className="rounded-3xl bg-white p-5"><h3 className="font-bold">Activities · {activities.length}</h3><div className="mt-4 grid gap-3 md:grid-cols-2">{activities.map(x => <div key={x.id} className="rounded-2xl border p-4"><b>{x.name}</b><p className="mt-1 text-xs text-slate-500">{x.category} · +{x.coin_reward} · limit {x.max_per_month ?? '∞'} · evidence {x.requires_evidence ? 'yes' : 'no'}</p></div>)}</div></div>}
        {tab === 'approvals' && <div className="rounded-3xl bg-white p-5"><h3 className="font-bold">Approvals</h3><div className="mt-4 space-y-3">{adminRequests.length ? adminRequests.map(x => <div key={x.id} className="rounded-2xl border p-4"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><b>{x.student?.full_name || 'Student'} · {x.activity?.name || 'Activity'}</b><p className="text-sm text-slate-500">+{x.activity?.coin_reward || 0} · {date(x.created_at)}</p>{x.evidence_url && <button type="button" onClick={() => void openEvidence(x.evidence_url!)} className="mt-2 inline-flex items-center gap-1 text-xs font-bold text-blue-700"><Upload className="h-3.5 w-3.5" />Evidence</button>}</div><div className="flex gap-2"><button type="button" disabled={busy} onClick={() => void approve(x.id,true)} className="rounded-xl bg-emerald-600 px-3 py-2 text-sm font-semibold text-white"><CheckCircle2 className="mr-1 inline h-4 w-4" />Tasdiqlash</button><button type="button" disabled={busy} onClick={() => void approve(x.id,false)} className="rounded-xl bg-red-50 px-3 py-2 text-sm font-semibold text-red-700"><XCircle className="mr-1 inline h-4 w-4" />Rad</button></div></div></div>) : <p className="text-sm text-slate-500">Kutilayotgan so‘rov yo‘q.</p>}</div></div>}
        {tab === 'market' && <div className="rounded-3xl bg-white p-5"><h3 className="font-bold">Market · {rewards.length}</h3><div className="mt-4 grid gap-3 md:grid-cols-2 lg:grid-cols-3">{rewards.map(x => <div key={x.id} className="rounded-2xl border p-4"><b>{x.title}</b><p className="mt-1 text-sm text-slate-500">{x.price} 🪙 · stock {x.stock}</p></div>)}</div></div>}
        {tab === 'orders' && <div className="rounded-3xl bg-white p-5"><h3 className="font-bold">Orders · {orders.length}</h3><div className="mt-4 space-y-3">{orders.map(x => <div key={x.id} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border p-4"><div><b>{x.reward_title}</b><p className="text-sm text-slate-500">{x.price} coin · {date(x.created_at)}</p></div><div className="flex flex-wrap gap-2"><button type="button" disabled={busy} onClick={() => void updateOrder(x.id,'approved')} className="rounded-xl bg-slate-900 px-3 py-2 text-xs font-semibold text-white">Approved</button><button type="button" disabled={busy} onClick={() => void updateOrder(x.id,'ready')} className="rounded-xl bg-amber-500 px-3 py-2 text-xs font-semibold text-white">Ready</button><button type="button" disabled={busy} onClick={() => void updateOrder(x.id,'delivered')} className="rounded-xl bg-emerald-600 px-3 py-2 text-xs font-semibold text-white">Delivered</button><button type="button" disabled={busy} onClick={() => void updateOrder(x.id,'rejected')} className="rounded-xl bg-red-50 px-3 py-2 text-xs font-semibold text-red-700">Rejected</button></div></div>)}</div></div>}
        {tab === 'transactions' && <div className="rounded-3xl bg-white p-5"><h3 className="font-bold">Transactions · {adminTransactions.length}</h3><div className="mt-4 space-y-2">{adminTransactions.map(x => <div key={x.id} className="flex items-center justify-between rounded-2xl bg-slate-50 p-3"><div><b>{x.transaction_type}</b><p className="text-xs text-slate-500">{x.note || x.student_id} · {date(x.created_at)}</p></div><span className={x.amount >= 0 ? 'font-black text-emerald-600' : 'font-black text-red-600'}>{x.amount > 0 ? '+' : ''}{x.amount}</span></div>)}</div></div>}
      </section></div>}
    </main></div>
    {selectedActivity && <div className="fixed inset-0 z-[150] grid place-items-center bg-slate-950/60 p-4"><section role="dialog" aria-modal="true" aria-labelledby="schoolcoin-activity-title" className="w-full max-w-lg rounded-3xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><h2 id="schoolcoin-activity-title" className="text-xl font-black">{selectedActivity.name}</h2><p className="mt-1 text-sm text-slate-500">+{selectedActivity.coin_reward} SchoolCoin</p></div><button type="button" onClick={() => setSelectedActivity(null)} aria-label="Yopish" className="rounded-xl p-2"><X /></button></div>{selectedActivity.requires_evidence && <p className="mt-5 rounded-2xl bg-blue-50 p-3 text-sm font-semibold text-blue-800">📎 Evidence majburiy — JPG, PNG, WebP yoki PDF, max 5 MB.</p>}<label className="mt-4 block text-sm font-semibold">Evidence<input type="file" accept="image/jpeg,image/png,image/webp,application/pdf" onChange={e => { const f=e.target.files?.[0]; if(f) void uploadEvidence(f).catch(err => fail(err,'Evidence yuklanmadi')); }} className="mt-2 block w-full rounded-2xl border p-3 text-sm" /></label>{evidenceName && <p className="mt-2 text-xs font-semibold text-emerald-700">✓ {evidenceName}</p>}<label className="mt-4 block text-sm font-semibold">Izoh<textarea value={note} onChange={e => setNote(e.target.value)} rows={3} className="mt-2 w-full rounded-2xl border p-3 text-sm" /></label><div className="mt-5 flex gap-2"><button type="button" onClick={() => setSelectedActivity(null)} className="flex-1 rounded-xl border px-4 py-3 text-sm font-semibold">Bekor qilish</button><button type="button" disabled={busy || (selectedActivity.requires_evidence && !evidencePath)} onClick={() => void submitActivity()} className="flex-1 rounded-xl bg-slate-900 px-4 py-3 text-sm font-semibold text-white disabled:opacity-40">{busy ? 'Yuborilmoqda…' : 'Yuborish'}</button></div></section></div>}
  </div>;
}
