import { useEffect, useMemo, useState } from 'react';
import { supabase, supabaseConfigured, signInAdmin } from '../lib/supabase';
import { Coins, Trophy, Gift, LogIn, LogOut, Plus, Check, X, ShieldCheck, ArrowUpRight } from 'lucide-react';

interface Props { onClose: () => void; }
type Student = { id:string; student_code:string; full_name:string; class_name:string; balance:number };

export default function SchoolCoin({ onClose }: Props) {
  const [mode,setMode]=useState<'student'|'admin'>('student');
  const [code,setCode]=useState(''); const [pin,setPin]=useState(''); const [student,setStudent]=useState<Student|null>(null);
  const [activities,setActivities]=useState<any[]>([]); const [rewards,setRewards]=useState<any[]>([]); const [transactions,setTransactions]=useState<any[]>([]);
  const [requests,setRequests]=useState<any[]>([]); const [students,setStudents]=useState<any[]>([]); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [notice,setNotice]=useState('');
  const [adminSession,setAdminSession]=useState<any>(null); const [adminEmail,setAdminEmail]=useState(''); const [adminPassword,setAdminPassword]=useState('');
  const [newStudent,setNewStudent]=useState({code:'',name:'',className:'',pin:''});

  const flash=(text:string)=>{setNotice(text);setTimeout(()=>setNotice(''),2200);};
  const loadCatalog=async()=>{ const [a,r]=await Promise.all([supabase.from('schoolcoin_activities').select('*').eq('active',true).order('category'),supabase.from('schoolcoin_rewards').select('*').eq('active',true).order('cost')]); if(a.error||r.error) setError((a.error||r.error)?.message||'Yuklashda xatolik'); else {setActivities(a.data||[]);setRewards(r.data||[]);} };
  const loginStudent=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{const {data,error}=await supabase.rpc('schoolcoin_student_login',{p_code:code,p_pin:pin});if(error)throw error;setStudent(data as Student);await loadCatalog();await loadStudentData(data as Student);}catch(err:any){setError(err.message||'Kirishda xatolik');}finally{setBusy(false);}};
  const loadStudentData=async(s:Student)=>{const {data,error}=await supabase.from('schoolcoin_transactions').select('*').eq('student_id',s.id).order('created_at',{ascending:false}).limit(20);if(!error)setTransactions(data||[]);};
  const submitRequest=async(activityId:string)=>{setBusy(true);setError('');try{const {error}=await supabase.rpc('schoolcoin_submit_request',{p_code:code,p_pin:pin,p_activity_id:activityId,p_evidence_url:null,p_note:null});if(error)throw error;flash('So‘rov yuborildi ✓');}catch(e:any){setError(e.message||'So‘rov yuborilmadi');}finally{setBusy(false);}};
  const redeem=async(rewardId:string)=>{setBusy(true);setError('');try{const {error}=await supabase.rpc('schoolcoin_redeem',{p_code:code,p_pin:pin,p_reward_id:rewardId});if(error)throw error;flash('Reward so‘rovi yuborildi ✓');}catch(e:any){setError(e.message||'Reward olishda xatolik');}finally{setBusy(false);}};
  const adminLogin=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{const result=await signInAdmin(adminEmail.trim(),adminPassword);setAdminSession(result.session);await loadAdmin();}catch(e:any){setError(e.message||'Admin kirishda xatolik');}finally{setBusy(false);}};
  const loadAdmin=async()=>{const [s,q,t]=await Promise.all([supabase.from('schoolcoin_students').select('id,student_code,full_name,class_name,created_at').order('created_at',{ascending:false}),supabase.from('schoolcoin_requests').select('id,status,evidence_url,note,created_at,student_id,activity_id,schoolcoin_students(full_name,student_code),schoolcoin_activities(name,coin_reward)').eq('status','pending').order('created_at',{ascending:false}),supabase.from('schoolcoin_transactions').select('id,student_id,amount,transaction_type,note,created_at,schoolcoin_students(full_name,student_code)').order('created_at',{ascending:false}).limit(50)]);if(s.error||q.error||t.error){setError((s.error||q.error||t.error)?.message||'Admin ma’lumotlari yuklanmadi');return;}setStudents(s.data||[]);setRequests(q.data||[]);setTransactions(t.data||[]);await loadCatalog();};
  const createStudent=async()=>{setBusy(true);setError('');try{const {error}=await supabase.rpc('schoolcoin_admin_create_student',{p_code:newStudent.code,p_full_name:newStudent.name,p_class:newStudent.className,p_pin:newStudent.pin});if(error)throw error;setNewStudent({code:'',name:'',className:'',pin:''});flash('O‘quvchi yaratildi ✓');await loadAdmin();}catch(e:any){setError(e.message||'O‘quvchi yaratilmadi');}finally{setBusy(false);}};
  const approve=async(id:string,yes:boolean)=>{setBusy(true);try{const {error}=await supabase.rpc('schoolcoin_admin_approve_request',{p_request_id:id,p_approve:yes});if(error)throw error;flash(yes?'Coin berildi ✓':'So‘rov rad etildi');await loadAdmin();}catch(e:any){setError(e.message||'Amal bajarilmadi');}finally{setBusy(false);}};
  const balanceMap=useMemo(()=>{const m:Record<string,number>={};transactions.forEach(t=>{m[t.student_id]=(m[t.student_id]||0)+Number(t.amount||0)});return m;},[transactions]);

  useEffect(()=>{if(mode==='student')loadCatalog();},[mode]);

  return <div className="fixed inset-0 z-[120] overflow-auto bg-slate-950/70 backdrop-blur-xl p-3 md:p-6">
    <div className="mx-auto min-h-[calc(100vh-24px)] max-w-6xl rounded-[32px] bg-slate-50 shadow-2xl overflow-hidden">
      <header className="sticky top-0 z-10 flex items-center justify-between gap-3 border-b bg-white/95 backdrop-blur px-5 py-4">
        <div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-amber-100 text-amber-600"><Coins/></div><div><h1 className="font-black text-xl">SchoolCoin</h1><p className="text-xs text-slate-500">Student economy & reward system</p></div></div>
        <div className="flex items-center gap-2"><button onClick={()=>setMode('student')} className={`rounded-xl px-3 py-2 text-sm font-semibold ${mode==='student'?'bg-slate-900 text-white':'bg-slate-100'}`}>Student</button><button onClick={()=>setMode('admin')} className={`rounded-xl px-3 py-2 text-sm font-semibold ${mode==='admin'?'bg-slate-900 text-white':'bg-slate-100'}`}>Admin</button><button onClick={onClose} className="rounded-xl p-2 hover:bg-slate-100"><X/></button></div>
      </header>
      <main className="p-5 md:p-7">
        {error&&<div className="mb-4 rounded-2xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}{notice&&<div className="mb-4 rounded-2xl bg-emerald-50 p-3 text-sm text-emerald-700">{notice}</div>}
        {mode==='student' && !student && <section className="mx-auto max-w-md rounded-3xl bg-white p-7 shadow-sm"><div className="mb-6 text-center"><Coins className="mx-auto h-10 w-10 text-amber-500"/><h2 className="mt-3 text-2xl font-black">Student Login</h2><p className="mt-1 text-sm text-slate-500">Kod va PIN orqali SchoolCoin hisobingizga kiring.</p></div><form onSubmit={loginStudent} className="space-y-3"><input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="Student code (SC-001)" className="w-full rounded-2xl border p-3.5" required/><input value={pin} onChange={e=>setPin(e.target.value)} type="password" placeholder="PIN" className="w-full rounded-2xl border p-3.5" required/><button disabled={busy} className="w-full rounded-2xl bg-slate-900 py-3.5 font-bold text-white disabled:opacity-50">{busy?'Kirilmoqda…':'Kirish'} <LogIn className="ml-1 inline h-4 w-4"/></button></form></section>}
        {mode==='student' && student && <div className="space-y-6"><section className="grid gap-4 md:grid-cols-3"><div className="md:col-span-2 rounded-3xl bg-slate-900 p-6 text-white"><p className="text-sm text-white/60">Salom, {student.full_name} 👋</p><h2 className="mt-1 text-3xl font-black">{student.balance} SchoolCoin</h2><p className="mt-2 text-sm text-white/60">{student.class_name} · {student.student_code}</p></div><button onClick={()=>{setStudent(null);setPin('');setCode('');}} className="rounded-3xl bg-white p-5 text-left shadow-sm"><LogOut className="h-5 w-5"/><p className="mt-3 font-bold">Chiqish</p></button></section><section><div className="mb-3 flex items-center justify-between"><h3 className="text-xl font-black">Coin olish</h3><span className="text-xs text-slate-500">Dalil kerak bo‘lishi mumkin</span></div><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3">{activities.map(a=><article key={a.id} className="rounded-3xl bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="font-bold">{a.name}</p><p className="mt-1 text-xs text-slate-500">{a.category}</p></div><span className="rounded-full bg-amber-100 px-3 py-1 text-sm font-black text-amber-700">+{a.coin_reward}</span></div><button disabled={busy} onClick={()=>submitRequest(a.id)} className="mt-4 w-full rounded-xl bg-amber-500 py-2.5 text-sm font-bold text-white">So‘rov yuborish</button></article>)}</div></section><section><h3 className="mb-3 text-xl font-black">Reward Store</h3><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3">{rewards.map(r=><article key={r.id} className="rounded-3xl bg-white p-5 shadow-sm"><Gift className="h-6 w-6 text-violet-500"/><p className="mt-3 font-bold">{r.name}</p><p className="mt-1 text-xs text-slate-500">{r.description}</p><div className="mt-4 flex items-center justify-between"><span className="font-black">{r.cost} 🪙</span><button disabled={busy} onClick={()=>redeem(r.id)} className="rounded-xl bg-slate-900 px-3 py-2 text-xs font-bold text-white">Redeem</button></div></article>)}</div></section><section><h3 className="mb-3 text-xl font-black">Oxirgi transactions</h3><div className="overflow-hidden rounded-3xl bg-white shadow-sm">{transactions.length?transactions.map(t=><div key={t.id} className="flex items-center justify-between border-b p-4 last:border-0"><span className="text-sm">{t.note||t.transaction_type}</span><b className={Number(t.amount)>0?'text-emerald-600':'text-red-600'}>{Number(t.amount)>0?'+':''}{t.amount}</b></div>):<p className="p-5 text-sm text-slate-500">Hali transaction yo‘q.</p>}</div></section></div>}
        {mode==='admin' && !adminSession && <section className="mx-auto max-w-md rounded-3xl bg-white p-7 shadow-sm"><ShieldCheck className="mx-auto h-10 w-10 text-blue-600"/><h2 className="mt-3 text-center text-2xl font-black">SchoolCoin Admin</h2><form onSubmit={adminLogin} className="mt-6 space-y-3"><input type="email" value={adminEmail} onChange={e=>setAdminEmail(e.target.value)} placeholder="Admin email" className="w-full rounded-2xl border p-3.5" required/><input type="password" value={adminPassword} onChange={e=>setAdminPassword(e.target.value)} placeholder="Parol" className="w-full rounded-2xl border p-3.5" required/><button disabled={busy} className="w-full rounded-2xl bg-blue-600 py-3.5 font-bold text-white">Kirish</button></form></section>}
        {mode==='admin' && adminSession && <div className="space-y-6"><section className="grid gap-4 md:grid-cols-3"><div className="rounded-3xl bg-white p-5 shadow-sm"><p className="text-xs text-slate-500">Students</p><p className="text-3xl font-black">{students.length}</p></div><div className="rounded-3xl bg-white p-5 shadow-sm"><p className="text-xs text-slate-500">Pending requests</p><p className="text-3xl font-black">{requests.length}</p></div><div className="rounded-3xl bg-white p-5 shadow-sm"><p className="text-xs text-slate-500">Transactions</p><p className="text-3xl font-black">{transactions.length}</p></div></section><section className="rounded-3xl bg-white p-6 shadow-sm"><h3 className="mb-4 text-xl font-black">O‘quvchi qo‘shish</h3><div className="grid gap-3 md:grid-cols-4"><input value={newStudent.code} onChange={e=>setNewStudent({...newStudent,code:e.target.value})} placeholder="SC-001" className="rounded-2xl border p-3"/><input value={newStudent.name} onChange={e=>setNewStudent({...newStudent,name:e.target.value})} placeholder="Ism-familiya" className="rounded-2xl border p-3"/><input value={newStudent.className} onChange={e=>setNewStudent({...newStudent,className:e.target.value})} placeholder="11-A" className="rounded-2xl border p-3"/><input value={newStudent.pin} onChange={e=>setNewStudent({...newStudent,pin:e.target.value})} placeholder="PIN" type="password" className="rounded-2xl border p-3"/></div><button disabled={busy} onClick={createStudent} className="mt-3 rounded-2xl bg-blue-600 px-5 py-3 font-bold text-white"><Plus className="mr-1 inline h-4 w-4"/> Qo‘shish</button></section><section className="rounded-3xl bg-white p-6 shadow-sm"><h3 className="mb-4 text-xl font-black">Pending requests</h3>{requests.length?requests.map(q=><div key={q.id} className="flex flex-col gap-3 border-b py-4 last:border-0 md:flex-row md:items-center md:justify-between"><div><p className="font-bold">{q.schoolcoin_students?.full_name} · {q.schoolcoin_activities?.name}</p><p className="text-xs text-slate-500">+{q.schoolcoin_activities?.coin_reward} coin · {new Date(q.created_at).toLocaleString()}</p></div><div className="flex gap-2"><button onClick={()=>approve(q.id,true)} className="rounded-xl bg-emerald-600 px-3 py-2 text-sm font-bold text-white"><Check className="mr-1 inline h-4 w-4"/>Approve</button><button onClick={()=>approve(q.id,false)} className="rounded-xl bg-red-50 px-3 py-2 text-sm font-bold text-red-700"><X className="mr-1 inline h-4 w-4"/>Reject</button></div></div>):<p className="text-sm text-slate-500">Pending request yo‘q.</p>}</section><section className="rounded-3xl bg-white p-6 shadow-sm"><h3 className="mb-4 text-xl font-black">Students</h3><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3">{students.map(s=><article key={s.id} className="rounded-2xl border p-4"><p className="font-bold">{s.full_name}</p><p className="text-xs text-slate-500">{s.student_code} · {s.class_name}</p></article>)}</div></section></div>}
      </main>
    </div>
  </div>;
}
