import { useEffect, useState } from 'react';
import { BedDouble, Utensils, Clock3, ChevronRight } from 'lucide-react';
import { getSiteData, supabase, supabaseConfigured } from '../lib/supabase';
import { useI18n } from '../i18n';

type SchoolLifeData = { dormitory?: { title?: string; description?: string; image?: string; features?: string[] }; meals?: { title?: string; description?: string; menu?: { name: string; time: string; description?: string }[] }; routine?: { title?: string; description?: string; items?: { time: string; activity: string; description?: string }[] } };
const fallback: SchoolLifeData = {
  dormitory: { title: 'Yotoqxona', description: 'O‘quvchilar uchun qulay, xavfsiz va tartibli yashash muhiti.', features: ['Qulay yashash sharoiti', 'Nazorat va xavfsizlik', 'Dam olish va mustaqil tayyorgarlik zonalari'] },
  meals: { title: 'Ovqatlanish', description: 'O‘quvchilar uchun kun davomida belgilangan vaqtlarda ovqatlanish tartibi.', menu: [{ name: 'Nonushta', time: '07:30' }, { name: 'Tushlik', time: '13:00' }, { name: 'Kechki ovqat', time: '18:30' }] },
  routine: { title: 'Kun tartibi', description: 'O‘quv, dam olish va mustaqil tayyorgarlik vaqtlarini muvozanatli tashkil etish.', items: [{ time: '06:30', activity: 'Uyg‘onish' }, { time: '07:30', activity: 'Nonushta' }, { time: '08:30', activity: 'Darslar' }, { time: '13:00', activity: 'Tushlik' }, { time: '15:00', activity: 'To‘garaklar / mustaqil ta’lim' }, { time: '18:30', activity: 'Kechki ovqat' }, { time: '22:00', activity: 'Uyqu' }] },
};

export default function SchoolLife() {
  const { locale } = useI18n();
  const [data, setData] = useState<SchoolLifeData>(fallback);
  useEffect(() => { let alive = true; const load = async () => { const value = await getSiteData('schoolLife', fallback); if (alive) setData(value || fallback); }; void load(); if (!supabaseConfigured) return () => { alive = false; }; const channel = supabase.channel('school-life-live').on('postgres_changes', { event: '*', schema: 'public', table: 'site_data' }, payload => { const key = (payload.new as { key?: string } | null)?.key || (payload.old as { key?: string } | null)?.key; if (key === 'schoolLife') void load(); }).subscribe(); return () => { alive = false; void supabase.removeChannel(channel); }; }, []);
  const copy = locale === 'ru' ? { eyebrow: 'Школьная жизнь', title: 'Жизнь за пределами уроков тоже важна.', desc: 'Информация о проживании, питании и распорядке дня в одном месте.', dorm: 'Общежитие', meals: 'Питание', routine: 'Распорядок дня' } : locale === 'en' ? { eyebrow: 'School life', title: 'Life beyond the classroom matters too.', desc: 'Everything about accommodation, meals, and the daily routine in one place.', dorm: 'Dormitory', meals: 'Meals', routine: 'Daily routine' } : { eyebrow: 'Maktab hayoti', title: 'Ta’limdan tashqari hayot ham muhim.', desc: 'Yotoqxona, ovqatlanish va kun tartibi haqida kerakli ma’lumotlar bir joyda.', dorm: 'Yotoqxona', meals: 'Ovqatlanish', routine: 'Kun tartibi' };
  return <section id="school-life" className="scroll-mt-24 bg-white py-16 text-slate-900 sm:py-20"><div className="mx-auto max-w-7xl px-5 sm:px-8 md:px-12 lg:px-16"><div className="mb-10 max-w-2xl"><p className="mb-3 text-sm font-semibold uppercase tracking-[0.2em] text-[#0071e3]">{copy.eyebrow}</p><h2 className="!text-slate-900 text-3xl font-bold tracking-tight sm:text-5xl">{copy.title}</h2><p className="mt-4 text-slate-600">{copy.desc}</p></div><div className="grid gap-5 lg:grid-cols-3">
    <article className="rounded-[30px] border border-slate-200 bg-white p-6 shadow-xl shadow-slate-900/5 transition duration-300 hover:-translate-y-1 hover:shadow-2xl motion-reduce:transition-none"><div className="mb-5 flex h-12 w-12 items-center justify-center rounded-2xl bg-blue-50 text-[#0071e3]"><BedDouble className="h-6 w-6" /></div><h3 className="text-xl font-bold text-slate-900">{data.dormitory?.title || copy.dorm}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{data.dormitory?.description}</p><ul className="mt-5 space-y-3">{(data.dormitory?.features || []).map((item, i) => <li key={`${item}-${i}`} className="flex items-center gap-2 text-sm text-slate-700"><ChevronRight className="h-4 w-4 text-[#0071e3]" />{item}</li>)}</ul>{data.dormitory?.image && <img src={data.dormitory.image} alt={copy.dorm} loading="lazy" decoding="async" className="mt-5 h-40 w-full rounded-2xl object-cover" />}</article>
    <article className="rounded-[30px] border border-slate-200 bg-white p-6 shadow-xl shadow-slate-900/5 transition duration-300 hover:-translate-y-1 hover:shadow-2xl motion-reduce:transition-none"><div className="mb-5 flex h-12 w-12 items-center justify-center rounded-2xl bg-amber-50 text-amber-600"><Utensils className="h-6 w-6" /></div><h3 className="text-xl font-bold text-slate-900">{data.meals?.title || copy.meals}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{data.meals?.description}</p><div className="mt-5 space-y-3">{(data.meals?.menu || []).map((item, i) => <div key={`${item.name}-${i}`} className="flex items-center justify-between rounded-2xl bg-slate-50 px-4 py-3"><div><p className="text-sm font-semibold text-slate-900">{item.name}</p>{item.description && <p className="text-xs text-slate-500">{item.description}</p>}</div><span className="font-bold text-[#0071e3]">{item.time}</span></div>)}</div></article>
    <article className="rounded-[30px] border border-slate-200 bg-white p-6 shadow-xl shadow-slate-900/5 transition duration-300 hover:-translate-y-1 hover:shadow-2xl motion-reduce:transition-none"><div className="mb-5 flex h-12 w-12 items-center justify-center rounded-2xl bg-violet-50 text-violet-600"><Clock3 className="h-6 w-6" /></div><h3 className="text-xl font-bold text-slate-900">{data.routine?.title || copy.routine}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{data.routine?.description}</p><div className="mt-5 max-h-72 space-y-2 overflow-auto pr-1">{(data.routine?.items || []).map((item, i) => <div key={`${item.time}-${i}`} className="flex gap-3 rounded-2xl border border-slate-100 bg-white px-4 py-3"><span className="w-14 shrink-0 font-bold text-[#0071e3]">{item.time}</span><div><p className="text-sm font-semibold text-slate-900">{item.activity}</p>{item.description && <p className="text-xs text-slate-500">{item.description}</p>}</div></div>)}</div></article>
  </div></div></section>;
}
