import { useEffect, useState } from 'react';
import { getSiteData, saveSiteData, signInAdmin, signOutAdmin, supabase } from '../lib/supabase';
import { X, ShieldCheck, Save, LogIn, LogOut, Plus, Trash2 } from 'lucide-react';

type Item = { time: string; activity: string; description?: string };
type Meal = { name: string; time: string; description?: string };
type Data = { dormitory: { title: string; description: string; image?: string; features: string[] }; meals: { title: string; description: string; menu: Meal[] }; routine: { title: string; description: string; items: Item[] } };
const empty: Data = { dormitory: { title: 'Yotoqxona', description: '', image: '', features: [] }, meals: { title: 'Ovqatlanish', description: '', menu: [] }, routine: { title: 'Kun tartibi', description: '', items: [] } };

export default function SchoolLifeAdmin({ onClose }: { onClose: () => void }) {
  const [session, setSession] = useState<any>(null); const [email, setEmail] = useState(''); const [password, setPassword] = useState('');
  const [data, setData] = useState<Data>(empty); const [feature, setFeature] = useState(''); const [meal, setMeal] = useState<Meal>({ name: '', time: '', description: '' }); const [routine, setRoutine] = useState<Item>({ time: '', activity: '', description: '' }); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  useEffect(() => { supabase.auth.getSession().then(({ data }) => setSession(data.session)); const { data: sub } = supabase.auth.onAuthStateChange((_e, s) => setSession(s)); return () => sub.subscription.unsubscribe(); }, []);
  useEffect(() => { if (session?.user?.app_metadata?.role === 'admin') void getSiteData('schoolLife', empty).then(v => setData(v || empty)).catch(() => undefined); }, [session]);
  const login = async (e: React.FormEvent) => { e.preventDefault(); setBusy(true); setError(''); try { const r = await signInAdmin(email.trim(), password); setSession(r.session); setPassword(''); } catch (e: any) { setError(e.message || 'Kirishda xatolik'); } finally { setBusy(false); } };
  const save = async () => { setBusy(true); setError(''); try { await saveSiteData('schoolLife', data); setNotice('Maktab hayoti saqlandi ✓'); setTimeout(() => setNotice(''), 2500); } catch (e: any) { setError(e.message || 'Saqlashda xatolik'); } finally { setBusy(false); } };
  const admin = session?.user?.app_metadata?.role === 'admin';
  if (!session || !admin) return <div className="fixed inset-0 z-[120] flex items-center justify-center bg-slate-950/70 backdrop-blur-xl p-4"><div className="w-full max-w-md rounded-[32px] bg-white p-7 shadow-2xl"><div className="flex items-center justify-between mb-7"><div><div className="flex items-center gap-2 text-[#0071e3] font-bold"><ShieldCheck className="h-5 w-5"/> Secure Admin</div><h2 className="mt-2 text-2xl font-bold">Maktab hayoti</h2></div><button onClick={onClose}><X/></button></div><form onSubmit={login} className="space-y-4"><input type="email" required value={email} onChange={e => setEmail(e.target.value)} placeholder="Admin email" className="w-full rounded-2xl border p-3.5"/><input type="password" required value={password} onChange={e => setPassword(e.target.value)} placeholder="Parol" className="w-full rounded-2xl border p-3.5"/>{error && <p className="text-sm text-red-600">{error}</p>}<button disabled={busy} className="w-full rounded-2xl bg-[#0071e3] py-3.5 text-white font-semibold">{busy ? 'Tekshirilmoqda…' : 'Kirish'} <LogIn className="inline h-4 w-4 ml-1"/></button></form></div></div>;
  return <div className="fixed inset-0 z-[120] overflow-auto bg-slate-100"><header className="sticky top-0 z-10 flex items-center justify-between border-b bg-white/90 px-5 py-3 backdrop-blur-xl"><div><h2 className="font-bold">Maktab hayoti boshqaruvi</h2><p className="text-xs text-slate-500">Yotoqxona · Ovqatlanish · Kun tartibi</p></div><div className="flex gap-2"><button onClick={() => void save()} disabled={busy} className="inline-flex items-center gap-2 rounded-xl bg-[#0071e3] px-4 py-2 text-sm font-semibold text-white"><Save className="h-4 w-4"/>Saqlash</button><button onClick={() => void signOutAdmin()} className="p-2"><LogOut className="h-5 w-5"/></button><button onClick={onClose} className="p-2"><X/></button></div></header><main className="mx-auto max-w-5xl space-y-5 p-5">{error && <div className="rounded-2xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}{notice && <div className="rounded-2xl bg-green-50 p-3 text-sm text-green-700">{notice}</div>}
    <section className="rounded-3xl bg-white p-5 shadow-sm"><h3 className="mb-4 text-lg font-bold">🛏️ Yotoqxona</h3><div className="grid gap-3 md:grid-cols-2"><input value={data.dormitory.title} onChange={e => setData(p => ({...p, dormitory: {...p.dormitory, title: e.target.value}}))} placeholder="Sarlavha" className="rounded-2xl border p-3"/><input value={data.dormitory.image || ''} onChange={e => setData(p => ({...p, dormitory: {...p.dormitory, image: e.target.value}}))} placeholder="Rasm URL" className="rounded-2xl border p-3"/><textarea value={data.dormitory.description} onChange={e => setData(p => ({...p, dormitory: {...p.dormitory, description: e.target.value}}))} placeholder="Tavsif" className="md:col-span-2 rounded-2xl border p-3"/><div className="md:col-span-2"><div className="flex gap-2"><input value={feature} onChange={e => setFeature(e.target.value)} placeholder="Yangi qulaylik" className="flex-1 rounded-2xl border p-3"/><button onClick={() => { if (!feature.trim()) return; setData(p => ({...p, dormitory: {...p.dormitory, features: [...p.dormitory.features, feature.trim()]}})); setFeature(''); }} className="rounded-2xl bg-slate-900 px-4 text-white"><Plus/></button></div><div className="mt-3 flex flex-wrap gap-2">{data.dormitory.features.map((x, i) => <span key={`${x}-${i}`} className="inline-flex items-center gap-1 rounded-full bg-slate-100 px-3 py-1 text-sm">{x}<button onClick={() => setData(p => ({...p, dormitory: {...p.dormitory, features: p.dormitory.features.filter((_, j) => j !== i)}})}><Trash2 className="h-3 w-3"/></button></span>)}</div></div></div></section>
    <section className="rounded-3xl bg-white p-5 shadow-sm"><h3 className="mb-4 text-lg font-bold">🍽️ Ovqatlanish</h3><input value={data.meals.title} onChange={e => setData(p => ({...p, meals: {...p.meals, title: e.target.value}}))} className="mb-3 w-full rounded-2xl border p-3" placeholder="Sarlavha"/><textarea value={data.meals.description} onChange={e => setData(p => ({...p, meals: {...p.meals, description: e.target.value}}))} className="mb-4 w-full rounded-2xl border p-3" placeholder="Tavsif"/><div className="grid gap-2 md:grid-cols-[1fr_140px_1fr_auto]"><input value={meal.name} onChange={e => setMeal(p => ({...p,name:e.target.value}))} placeholder="Masalan: Nonushta" className="rounded-2xl border p-3"/><input value={meal.time} onChange={e => setMeal(p => ({...p,time:e.target.value}))} placeholder="07:30" className="rounded-2xl border p-3"/><input value={meal.description || ''} onChange={e => setMeal(p => ({...p,description:e.target.value}))} placeholder="Izoh" className="rounded-2xl border p-3"/><button onClick={() => { if (!meal.name.trim() || !meal.time.trim()) return; setData(p => ({...p, meals:{...p.meals, menu:[...p.meals.menu, meal]}})); setMeal({name:'',time:'',description:''}); }} className="rounded-2xl bg-slate-900 px-4 text-white"><Plus/></button></div><div className="mt-3 space-y-2">{data.meals.menu.map((x,i)=><div key={`${x.name}-${i}`} className="flex items-center justify-between rounded-2xl bg-slate-50 p-3"><span><b>{x.name}</b> · {x.time}{x.description ? ` — ${x.description}` : ''}</span><button onClick={() => setData(p => ({...p,meals:{...p.meals,menu:p.meals.menu.filter((_,j)=>j!==i)}})}><Trash2 className="h-4 w-4 text-red-500"/></button></div>)}</div></section>
    <section className="rounded-3xl bg-white p-5 shadow-sm"><h3 className="mb-4 text-lg font-bold">🕐 Kun tartibi</h3><input value={data.routine.title} onChange={e => setData(p => ({...p,routine:{...p.routine,title:e.target.value}}))} className="mb-3 w-full rounded-2xl border p-3" placeholder="Sarlavha"/><textarea value={data.routine.description} onChange={e => setData(p => ({...p,routine:{...p.routine,description:e.target.value}}))} className="mb-4 w-full rounded-2xl border p-3" placeholder="Tavsif"/><div className="grid gap-2 md:grid-cols-[120px_1fr_1fr_auto]"><input value={routine.time} onChange={e => setRoutine(p=>({...p,time:e.target.value}))} placeholder="08:30" className="rounded-2xl border p-3"/><input value={routine.activity} onChange={e => setRoutine(p=>({...p,activity:e.target.value}))} placeholder="Darslar" className="rounded-2xl border p-3"/><input value={routine.description || ''} onChange={e => setRoutine(p=>({...p,description:e.target.value}))} placeholder="Izoh" className="rounded-2xl border p-3"/><button onClick={() => { if(!routine.time.trim()||!routine.activity.trim()) return; setData(p=>({...p,routine:{...p.routine,items:[...p.routine.items,routine]}})); setRoutine({time:'',activity:'',description:''}); }} className="rounded-2xl bg-slate-900 px-4 text-white"><Plus/></button></div><div className="mt-3 space-y-2">{data.routine.items.map((x,i)=><div key={`${x.time}-${i}`} className="flex items-center justify-between rounded-2xl bg-slate-50 p-3"><span><b className="text-[#0071e3]">{x.time}</b> · {x.activity}{x.description ? ` — ${x.description}` : ''}</span><button onClick={() => setData(p=>({...p,routine:{...p.routine,items:p.routine.items.filter((_,j)=>j!==i)}})}><Trash2 className="h-4 w-4 text-red-500"/></button></div>)}</div></section>
  </main></div>;
}
